---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-csi
  labels:
    namespace: nfs-csi
    istio-injection: disabled
---
# Default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: nfs-csi
spec:
  podSelector: {}
---
# Allow all traffic within the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-within-namespace
  namespace: nfs-csi
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
