apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv2medvfiler3-pafa-prod
  namespace: medresponse-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  selector:
    matchLabels:
      volname: medresponse-prod-pv2medvfiler3-pafa-prod