apiVersion: v1
kind: ConfigMap
metadata:
  name: grav-ee-license
  namespace: gravitee
binaryData:
  license.key: Ic5OXgAAACAAAAACAAAADAAAAAhhbGVydC1lbmdpbmVpbmNsdWRlZAAAABwAAAACAAAABwAAAAljb21wYW55TWVkSW1wYWN0AAAAHQAAAAIAAAAHAAAACmVkaXRpb25lbnRlcnByaXNlAAAAKgAAAAIAAAAFAAAAGWVtYWlsaGFycnkuc21pdGhAbWVkaW1wYWN0LmNvbQAAABoAAAALAAAACmV4cGlyeURhdGUAAAF0RvaX/wAAACEAAAAMAAAACWxpY2Vuc2VJZKq67AAzEcZUoinH7TCRRIMAAAEcAAAAAQAAABAAAAEAbGljZW5zZVNpZ25hdHVyZS47ZjQrbVHpVn4Sz7Oae+E8jMiVml8Jl8Ag0IbFy1jNt5vYe6j/qO4FtpS+gJQ7tG4g8lp9uepMTnvWXoSVpgwXh8sPGYX+kbySyHKO8pEH90HQOMmM6Er+/uDLyX1PIwyyeH/matKNVhzKFbYx1YWzmwlqvotNFsSu1XzxlYdsltv6+nU4HjhdrslvXnnBnBNAN8ukayJeiQ6hLySG6Hy141LvzdnKYTMbnER8EpKjRRzD0imaI6NGobJOhKbPr7siW5eizpLOeQBBD8qLlhLx+qr1NKc02zYDWuH7+eyeCpXRytACyZYCIlXwo96ktlT/sZEhLXFniqkvYGehPwMAAAAiAAAAAgAAAA8AAAAHc2lnbmF0dXJlRGlnZXN0U0hBLTUxMg==
