apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: fluentd
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
      kubernetes.io/cluster-service: "true"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluentd
      tolerations:
      - operator: Exists
      # - key: node-role.kubernetes.io/master
        # effect: NoSchedule
      # - key: dmz
        # effect: NoExecute
        # operator: Exists
      containers:
      - name: fluentd
        image: docker-local.artifactory.medimpact.com/systems/k8s-fluentd:v1.0.3
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - set -x;
          find /var/log/fluentd* -name 'storage.json' -exec sh -c "if [ ! -s {} ]; then rm -rf {};fi" \;;
          "/fluentd/entrypoint.sh"
        envFrom:
        - secretRef:
            name: splunk-hec-tokens
        env:
        # K8S_NODE_NAME decreases resource consumption if watch is enabled. Also used to insert "K8S_NODE" key in logs - see config.
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # Fluentd will use this env to set the "K8S_CLUSTER" key in logs - see config
        - name:  K8S_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: clustername
              key: splunk_k8s_clustername
        - name:  ROLLOUT
          value: "0"
        - name:  FLUENT_UID
          value: "0"
        - name: FLUENT_POS_PATH
          value: "/var/log/fluentd"
        - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
          value: "/^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<MESSAGE>.*)$/"
        - name:  FLUENT_SPLUNK_HEC_PORT
          value: "8088"
        - name:  FLUENT_SPLUNK_HEC_SOURCE
          value: "fluentd-splunkhec"
        - name:  FLUENT_SPLUNK_HEC_SOURCE_TYPE
          value: "fluentd-splunkhec"
        - name:  FLUENT_SPLUNK_HEC_USE_FLUENTD_TIME
          value: "true"
        - name:  FLUENT_SPLUNK_HEC_TIME_AS_INTEGER
          value: "false"
        - name:  FLUENT_SPLUNK_HEC_USE_ACK
          value: "false"
        - name:  FLUENT_SPLUNK_HEC_ACK_INTERVAL
          value: "1"
        - name:  FLUENT_SPLUNK_HEC_ACK_RETRY_LIMIT
          value: "3"
        - name:  FLUENT_SPLUNK_HEC_USE_SSL
          value: "true"
        - name:  FLUENT_SPLUNK_HEC_SSL_VERIFY
          value: "false"
        - name:  FLUENT_SPLUNK_HEC_CA_FILE
          value: ""
        - name:  FLUENT_SPLUNK_HEC_FLUSH_INTERVAL
          value: "10s"
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: runlogjournal
          mountPath: /run/log/journal
        - name: config
          mountPath: /fluentd/etc
        - name: auditlogs
          mountPath: /opt/app/kubernetes/audit/logs
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: runlogjournal
        hostPath:
          path: /run/log/journal
      - name: config
        configMap:
          defaultMode: 420
          name: fluentd
      - name: auditlogs
        hostPath:
          path: /opt/app/kubernetes/audit/logs