apiVersion: v1
kind: Secret
metadata:
  name: star-fullchain.medimpact.com.tls
  namespace: ingress-nginx
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGpzCCBY+gAwIBAgIQKDGVAvUXVIbPxFtHslo7jzANBgkqhkiG9w0BAQsFADCB
    ujELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsT
    H1NlZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAy
    MDEyIEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEuMCwG
    A1UEAxMlRW50cnVzdCBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSAtIEwxSzAeFw0y
    MzEwMDMxNzEwMzhaFw0yNDEwMjkxNzEwMzdaMH0xCzAJBgNVBAYTAlVTMRMwEQYD
    VQQIEwpDYWxpZm9ybmlhMRIwEAYDVQQHEwlTYW4gRGllZ28xKzApBgNVBAoTIk1l
    ZEltcGFjdCBIZWFsdGhjYXJlIFN5c3RlbXMsIEluYy4xGDAWBgNVBAMMDyoubWVk
    aW1wYWN0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMv1NMQH
    kOcN3UDX6t/zwXSVyuiSXzZBdeLDgbzLpTmAgKCmXxyiOP7P20w6GIHTO46TXwqb
    wcZr+aK9BPtDfmHVr8YwmX3NR4VzL/HYIMf+KGpveAwh+iYlJ1tsvGTcY/nF1cj6
    R95Ef78xf5D/JSCWoA4POBcLQmsxMqK9Oq8yWpAnjGvpZcj6ZfyTWVW9nxiSV+b9
    cXglSfzIU5wh51EbD2jqbM7M+N7WyJVJaqdKGs/sYWnvGfH+cfMUXXcMem/avAxx
    Fj2C68moIOTlv2+7Q8SK2he5fs7Hxq4ZL24JEvanpi/ajSpc9UKI+VJqp6xjsgg6
    Et0dzER5D6fmJOsCAwEAAaOCAuMwggLfMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYE
    FInsM99d541XCDV88FJ6mVyxZMNSMB8GA1UdIwQYMBaAFIKicHTdvFM/z3vU981/
    p2DGCky/MGgGCCsGAQUFBwEBBFwwWjAjBggrBgEFBQcwAYYXaHR0cDovL29jc3Au
    ZW50cnVzdC5uZXQwMwYIKwYBBQUHMAKGJ2h0dHA6Ly9haWEuZW50cnVzdC5uZXQv
    bDFrLWNoYWluMjU2LmNlcjAzBgNVHR8ELDAqMCigJqAkhiJodHRwOi8vY3JsLmVu
    dHJ1c3QubmV0L2xldmVsMWsuY3JsMCkGA1UdEQQiMCCCDyoubWVkaW1wYWN0LmNv
    bYINbWVkaW1wYWN0LmNvbTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMBMGA1UdIAQMMAowCAYGZ4EMAQICMIIBfwYKKwYBBAHW
    eQIEAgSCAW8EggFrAWkAdwA/F0tP1yJHWJQdZRyEvg0S7ZA3fx+FauvBvyiF7Phk
    bgAAAYr2hTGqAAAEAwBIMEYCIQD3qQW55SGsjbRaD1IlsF7AOXkv1b12e29NGo5B
    sjFbZAIhALUuLcb+3LWdHz/OdkQ9ysSMp8HL2mmxF53BVlF7eYJMAHYA7s3QZNXb
    Gs7FXLedtM0TojKHRny87N7DUUhZRnEftZsAAAGK9oUx8AAABAMARzBFAiAokyOf
    yJAJNGtaLWGiu3HZiZoT4plYyEDZz4T0iwDkCAIhAKNG4d7E0aVMN4Bvy9sUImL+
    nrNzTVL+SAFbh5KWe4NSAHYA2ra/az+1tiKfm8K7XGvocJFxbLtRhIU0vaQ9MEjX
    +6sAAAGK9oUx5gAABAMARzBFAiACHbRQwJiPHe4gxmM6GuIlDS2/ruo5DzggSnsC
    1xT+jwIhAJtnqkOhnefoqhZiVGsjC9vn1skkGsAskoUYOVCcXTfSMA0GCSqGSIb3
    DQEBCwUAA4IBAQAWoRUnjLgO7tPr4jy3+18/7perzv8//S5nM4tXyYBFoMCICWAs
    YUfdi7X3aUx1Z8pYiNz4oWpFvNVbnPI48LChH0B6jbXUUy6urI2sRUDZhT+pSBey
    4tto3A3Oq6GqTSsJxQixI4d2sbeFj+DRX2xRlyWHkfzjUzJ66CTisl4431NEg+KD
    6iB+qIAWovna1anSVUePGT1uJ8PT+W1fbvksY1GA+a6dSwiW28IrKw8/fEXiPkv9
    3tPYYI3KXLawBwJUyCOX8X3j5U+6ehJmx0C9b+K9PNwf8VKRxHR3z24PitnI10pJ
    lz3Phx4meu8A12KdB4+nm4k3VYiATOOFn+nn
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFAzCCA+ugAwIBAgIEUdNg7jANBgkqhkiG9w0BAQsFADCBvjELMAkGA1UEBhMC
    VVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50
    cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3Qs
    IEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVz
    dCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwHhcNMTQxMDIyMTcw
    NTE0WhcNMjQxMDIzMDczMzIyWjCBujELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVu
    dHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwt
    dGVybXMxOTA3BgNVBAsTMChjKSAyMDEyIEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0
    aG9yaXplZCB1c2Ugb25seTEuMCwGA1UEAxMlRW50cnVzdCBDZXJ0aWZpY2F0aW9u
    IEF1dGhvcml0eSAtIEwxSzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    ANo/ltBNuS9E59s5XptQ7lylYdpBZ1MJqgCajld/KWvbx+EhJKo60I1HI9Ltchbw
    kSHSXbe4S6iDj7eRMmjPziWTLLJ9l8j+wbQXugmeA5CTe3xJgyJoipveR8MxmHou
    fUAL0u8+07KMqo9Iqf8A6ClYBve2k1qUcyYmrVgO5UK41epzeWRoUyW4hM+Ueq4G
    RQyja03Qxr7qGKQ28JKyuhyIjzpSf/debYMcnfAf5cPW3aV4kj2wbSzqyc+UQRlx
    RGi6RzwE6V26PvA19xW2nvIuFR4/R8jIOKdzRV1NsDuxjhcpN+rdBQEiu5Q2Ko1b
    Nf5TGS8IRsEqsxpiHU4r2RsCAwEAAaOCAQkwggEFMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMECDAGAQH/AgEAMDMGCCsGAQUFBwEBBCcwJTAjBggrBgEFBQcwAYYXaHR0
    cDovL29jc3AuZW50cnVzdC5uZXQwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL2Ny
    bC5lbnRydXN0Lm5ldC9nMmNhLmNybDA7BgNVHSAENDAyMDAGBFUdIAAwKDAmBggr
    BgEFBQcCARYaaHR0cDovL3d3dy5lbnRydXN0Lm5ldC9ycGEwHQYDVR0OBBYEFIKi
    cHTdvFM/z3vU981/p2DGCky/MB8GA1UdIwQYMBaAFGpyJnrQHu995ztpUdRsjZ+Q
    EmarMA0GCSqGSIb3DQEBCwUAA4IBAQA/HBpb/0AiHY81DC2qmSerwBEycNc2KGml
    jbEnmUK+xJPrSFdDcSPE5U6trkNvknbFGe/KvG9CTBaahqkEOMdl8PUM4ErfovrO
    GhGonGkvG9/q4jLzzky8RgzAiYDRh2uiz2vUf/31YFJnV6Bt0WRBFG00Yu0GbCTy
    BrwoAq8DLcIzBfvLqhboZRBD9Wlc44FYmc1r07jHexlVyUDOeVW4c4npXEBmQxJ/
    B7hlVtWNw6f1sbZlnsCDNn8WRTx0S5OKPPEr9TVwc3vnggSxGJgO1JxvGvz8pzOl
    u7sY82t6XTKH920l5OJ2hiEeEUbNdg5vT6QhcQqEpy02qUgiUX6C
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEPjCCAyagAwIBAgIESlOMKDANBgkqhkiG9w0BAQsFADCBvjELMAkGA1UEBhMC
    VVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50
    cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3Qs
    IEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVz
    dCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwHhcNMDkwNzA3MTcy
    NTU0WhcNMzAxMjA3MTc1NTU0WjCBvjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVu
    dHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwt
    dGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0
    aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVzdCBSb290IENlcnRpZmlj
    YXRpb24gQXV0aG9yaXR5IC0gRzIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC6hLZy254Ma+KZ6TABp3bqMriVQRrJ2mFOWHLP/vaCeb9zYQYKpSfYs1/T
    RU4cctZOMvJyig/3gxnQaoCAAEUesMfnmr8SVycco2gvCoe9amsOXmXzHHfV1IWN
    cCG0szLni6LVhjkCsbjSR87kyUnEO6fe+1R9V77w6G7CebI6C1XiUJgWMhNcL3hW
    wcKUs/Ja5CeanyTXxuzQmyWC48zCxEXFjJd6BmsqEZ+pCm5IO2/b1BEZQvePB7/1
    U1+cPvQXLOZprE4yTGJ36rfo5bs0vBmLrpxR57d+tVOxMyLlbc9wPBr64ptntoP0
    jaWvYkxN4FisZDQSA/i2jZRjJKRxAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRqciZ60B7vfec7aVHUbI2fkBJmqzAN
    BgkqhkiG9w0BAQsFAAOCAQEAeZ8dlsa2eT8ijYfThwMEYGprmi5ZiXMRrEPR9RP/
    jTkrwPK9T3CMqS/qF8QLVJ7UG5aYMzyorWKiAHarWWluBh1+xLlEjZivEtRh2woZ
    Rkfz6/djwUAFQKXSt/S1mja/qYh2iARVBCuch38aNzx+LaUa2NSJXsq9rD1s2G2v
    1fN2D807iDginWyTmsQ9v4IbZT+mD12q/OWyFcq1rca8PdCE6OoGcrBNOTJ4vz4R
    nAuknZoh8/CbCzB428Hch0P+vGOaysXCHMnHjf87ElgI5rY97HosTvuDls4MPGmH
    VHOkc8KT/1EQrBVUAdj8BbGJoX90g5pJ19xOe4pIb4tF9g==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDL9TTEB5DnDd1A
    1+rf88F0lcrokl82QXXiw4G8y6U5gICgpl8cojj+z9tMOhiB0zuOk18Km8HGa/mi
    vQT7Q35h1a/GMJl9zUeFcy/x2CDH/ihqb3gMIfomJSdbbLxk3GP5xdXI+kfeRH+/
    MX+Q/yUglqAODzgXC0JrMTKivTqvMlqQJ4xr6WXI+mX8k1lVvZ8Yklfm/XF4JUn8
    yFOcIedRGw9o6mzOzPje1siVSWqnShrP7GFp7xnx/nHzFF13DHpv2rwMcRY9guvJ
    qCDk5b9vu0PEitoXuX7Ox8auGS9uCRL2p6Yv2o0qXPVCiPlSaqesY7IIOhLdHcxE
    eQ+n5iTrAgMBAAECggEAd9jYbrA7d2nwLyAxRfPII6e5mbwY8pq4mM1lOPk5V3ap
    Hr1kekDg2Opu5HXm3LKw9nCmkmdAEEZ2ZChJ+xOH+hlEtmLsbr3nXwV2kNf9O0ef
    nBtwIUD96tg+LjzQ3zuaC7UykGxxOqxpnIGLgjpLKMEZv+k1fmUBXFeGd5ZWG4eg
    jvl2+JbCG79e0YBt1Glr51jRswnAOliW18KubzYCTEPbaVnVUUhyx93eQ7in5CNj
    n3ibp6CvzSO3CLfj40FlumoBjjAtRXw2kQkmZOTcGdfPiD5zG34NhHiSGWO2K8oj
    qBr8096PUsqoINkp+bHoHEfPnfB3+PGPX/Ch740HgQKBgQDpwjKGPoQvHZN9qoaL
    rKHloUC3jCVDyVpUV3AI45hvfc/OTl6fghEXRRoEQVj5mgn1KMGZE6LcFfvCm7tp
    ObbBH+VxHpacsKESmIrVgxspJKu/EUIAoNIXUcE/p8+SKZ3y9Qz71jGdwC5YlMo7
    VDPZXcuYNgFMlZYGW5p0UjzyoQKBgQDfXSIs1uzEa4xiDy4PKSIapjTV0OWIITTO
    9FJjMrelTnyYWjVx4zKiTL2CtIy3bnhf0GF/khWTS7vR8iNNv7Z660MA7S1ZAXwn
    F/0BDEgCAbKx8ZYSlMwWzzCF+XjhwSA1wXNHWR5uQXjfh84eiZNeYujo+eGEtg6O
    5bEjSmS4CwKBgQDjFN0iHj8oyhGKpYqYyzZnLZQB+qoExOj0QBC9AeQGgvDJmMZB
    LAhQU7enZJf7udFskJAplbLDHLP65HBWE1PfHo40qqNjSg7fUsKkEf3jpRUWwrwc
    gh41ux0BKpLxiW5AJB/d0cFXXudm8/vVUMIhqgVrMyNl83bPbFOKJo3AoQKBgGGs
    Ji+ZZDuYE/ElVizG/eTNXTlKebSHYMJG0GgUW33rzkwI1moQwal7CTvIm+fyZKzx
    QFE6njik22K5EXsEJFWn3sre6/+JyLKHqNj2d954w51QWSGS85Pd0ggjyRpfCyi2
    iSRf8hCgjKyihB2SZ2DUu6h07IrN2ZvfERCvjU91AoGBAJRLqQIYW/2DEorPlpnm
    C/ItBIyJ+c9w08lvqbyjto0p7KsJwCHnplP2IeaW/kmup/TiEhJyyGDteclYqFXd
    AbdEXNl2/BmwRYFcDdFq+LPpPjdXrTSsKyoNBr5VAOLzV9Y2PMMguFFbZYY4b8MU
    6pomy6VHaC7YvO3rkptm3Opr
    -----END PRIVATE KEY-----
