apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: vmware-system-csi
type: Opaque
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = "cadev"
    cluster-distribution = "kubeadm"
    #ca-file = <ca file path> # optional, use with insecure-flag set to false
    #thumbprint = "<cert thumbprint>" # optional, use with insecure-flag set to false without providing ca-file
    
    # VMWare CSI does not currently support multiple vcenters
    [VirtualCenter "pv1medvcenter2.medimpact.com"]
    insecure-flag = "true"
    # user = "MEDNT\\svcVMWareCSI"
    user = "svcVMWareCSI@medimpact.com"
    password = "ong8aug9UmaC_ae"
    port = "443"
    #datacenters = "<datacenter1-path>, <datacenter2-path>, ..."
    datacenters = "KIO Data Center"
    
    # [VirtualCenter "pv2medvcenter2.medimpact.com"]
    # insecure-flag = "true"
    # user = "MEDNT\\svcVMWareCSI"
    # password = "ong8aug9UmaC_ae"
    # port = "443"
    # #datacenters = "<datacenter1-path>, <datacenter2-path>, ..."
    # datacenters = "Tempe Data Center"
    
    [Labels]
    region = k8s-region
    zone = k8s-zone
    [TopologyCategory "k8s-region"]
    Label = "topology.kubernetes.io/region"
    [TopologyCategory "k8s-zone"]
    Label = "topology.kubernetes.io/zone"
    
    # [Labels]
    # topology-categories = "k8s-region,k8s-zone"