---
# Metrics Permissions quickfix
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: medimpact:namespaced-metrics-reader
  labels:
    # Add these permissions to the "admin" default ClusterRole.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - list