---
apiVersion: v1
kind: Namespace
metadata:
  name: bia-qa
  labels:
    istio-injection: disabled
    namespace: bia-qa
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pss-enforce: "true"
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: bia-qa
spec:
  hard:
    limits.cpu: 60000m
    limits.memory: 34G
    requests.cpu: 12000m
    requests.memory: 18G
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: bia-qa
spec:
  limits:
  - default:
      cpu: 150m
      memory: 125M
      ephemeral-storage: 5Gi
    defaultRequest:
      cpu: 50m
      memory: 100M
      ephemeral-storage: 100Mi
    max:
      ephemeral-storage: 10Gi
    type: Container
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: bia-qa
spec:
  podSelector: {}
---
# Allow istio prometheus to istio sidecars
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-istio-telemetry
  namespace: bia-qa
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: istio-system
        podSelector:
          matchLabels:
            app: prometheus
      ports:
      - port: 15090
        protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
---
#bind AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_qa_bia-qa
  namespace: bia-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kube_dev_bia-qa
---
#bind power-users AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_cluster-power-users
  namespace: bia-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kube_cluster-power-users
