# Create namespace admins cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: medimpact:namespace-admin
rules:
- apiGroups:
  - 'autoscaling'
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - configmaps
  - cronjobs
  - deployments
  - deployments/rollback
  - deployments/scale
  - endpoints
  - events
  - jobs
  - ingresses
  - horizontalpodautoscalers
  - limitranges
  - networkpolicies
  - persistentvolumeclaims
  - poddisruptionbudgets
  - pods
  - pods/exec
  - pods/attach
  - pods/log
  - pods/portforward
  - pods/status
  - podtemplates
  - replicasets
  - replicasets/scale
  - replicationcontrollers
  - services
  - secrets
  - statefulsets
  - statefulsets/scale
  verbs:
  - '*'
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - '*'
  resources:
  - daemonsets
  - namespaces
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
# - apiGroups:
  # - 'networking.istio.io'
  # resources:
  # - destinationrules
  # - gateways
  # - serviceentries
  # - virtualservices
  # verbs:
  # - '*'
# - apiGroups:
  # - 'authentication.istio.io'
  # resources:
  # - policies
  # verbs:
  # - '*'
