apiVersion: v1
kind: Secret
metadata: 
    name: install-mi-cacerts
    namespace: kube-system
type: Opaque
stringData:
  setup.sh: |
    echo "$MEDIMPACT_SUBCA1_2032" > /usr/local/share/ca-certificates/medimpact-subca1-2032.crt && echo "$MEDIMPACT_SUBCA2_2032" > /usr/local/share/ca-certificates/medimpact-subca2-2032.crt && echo "$MEDIMPACT_ROOT_2045" > /usr/local/share/ca-certificates/medimpact-root-2045.crt && update-ca-certificates && systemctl restart containerd
  medimpact-subca1-2032.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGdDCCBFygAwIBAgITPwAAABFBzSsoYG+SHwACAAAAETANBgkqhkiG9w0BAQsF
    ADAvMS0wKwYDVQQDEyRNZWRJbXBhY3QgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkwHhcNMjUwMzMxMTYwNjI3WhcNMzIwMzMxMTYxNjI3WjBLMRMwEQYKCZImiZPy
    LGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJbWVkaW1wYWN0MRkwFwYDVQQDExBN
    ZWRJbXBhY3QtU3ViQ0ExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    mynUO7qNtWSTHi3/pIdNw8SLeUn0uQI04pQs5gzihGCwFcR/gCR6ShrPiVOJmVbg
    MzYQPtRiJ7LNEYZFEncCZsq/Rb8q+Ca/SnqEgFbi7JJkuoIRN4ccQ6sKh9JCIjhh
    L/GiWSgqrQU1bccvPk7W3FOD99eV+4IfVX2+o6mwUyfM8085w2TTT5GvE6eAwvX9
    M2RNaO3tkzHoBTvZkNsNyYAUSjZ0Re4JViF8faAnYym0fakrnA3IparoFOyy4otm
    Z4IUlQMpAssJFzt3CUJC4G1xKzgdZLvhLUzMEXYysVUPklTHM85wTO93unCJRTuI
    obKF2JjS8tyXXeK3kfR9lQIDAQABo4ICazCCAmcwEAYJKwYBBAGCNxUBBAMCAQEw
    IwYJKwYBBAGCNxUCBBYEFP0U9xyC9nLtzjVzKvI20nA9cd6CMB0GA1UdDgQWBBQv
    z0gFWVqJWOB+W5dCwTfKzvfPTzAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
    BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTvtQvVxg1U
    hOCfZpsJ5k+jmIedyDBjBgNVHR8EXDBaMFigVqBUhlJodHRwOi8vY3JsLm1lZGlt
    cGFjdC5jb20vQ2VydEVucm9sbC9NZWRJbXBhY3QlMjBSb290JTIwQ2VydGlmaWNh
    dGUlMjBBdXRob3JpdHkuY3JsMIIBTgYIKwYBBQUHAQEEggFAMIIBPDCBywYIKwYB
    BQUHMAKGgb5sZGFwOi8vL0NOPU1lZEltcGFjdCUyMFJvb3QlMjBDZXJ0aWZpY2F0
    ZSUyMEF1dGhvcml0eSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMs
    Q049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1NZWRpbXBhY3QsREM9Y29t
    P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
    aG9yaXR5MGwGCCsGAQUFBzABhmBodHRwOi8vY3JsLm1lZGltcGFjdC5jb20vQ2Vy
    dEVucm9sbC9wdjFtZWRvY2ExX01lZEltcGFjdCUyMFJvb3QlMjBDZXJ0aWZpY2F0
    ZSUyMEF1dGhvcml0eSgyKS5jcnQwDQYJKoZIhvcNAQELBQADggIBADaHSkHTMqAM
    h6HojSb2iNYMFFT68Wyv7Kg93sJOhjTc7nIkY3VysZ7nAyS8cuLiNWcam0eE1Anf
    KddfmWMq78Vg2OxOWn8P/JEJSiJe8kTyhgpsOoskxFSoA8TColMkyj/lHaj3HNL2
    dIwPfAVBpEIwcXQaxAgEvsbbI+N8g/gLeV2PDlNuAawX3R1K6tp8vU4TnnIxszdX
    BJZ5rTjFlETRMYfC2ksPnS+cQcPeKhnAlCWcjJl0aQ2IACr8Q91NUR6qm8gOtLlJ
    CzWtPSHWKB8PsUg+eAKLhn1l8vwyLfujmuYlQUFcazdULAIgnqvOZ6wVN3Gf5yx1
    KNyu6E8NvP1xf5KDkYuVelsNhl3kH4gflFa61mldpBTuov3cRENx3XIitrfzEAdY
    6BL6okEt0CNt/qjlnRzIUA/36ZLgU4Ro3tbl9p+7zvAITAitMhsU2/YXHSu+CKG2
    LbTQcP5VxXY7Q9oxgQVpj+rbmHKecDMge+F4dDamYIH5sRu4zLsCK7a1BcO2C+ZT
    SL35qGTu7Ivqh/VfX48lbQrKenT6mSvktZCb8joACx0oEkiSs2iEMIvNCbVU0Rx2
    5mjb4GHQFT+cHBPxLXcCjxv22LfmfxYpmko+ENml6JAyhC1XLi1CsdkvKsWdXrlF
    nHus3F2yB/VyhwNVX3uxVLwy8qXahaQk
    -----END CERTIFICATE-----
  medimpact-subca2-2032.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGdDCCBFygAwIBAgITPwAAABJPweV0c56kTwACAAAAEjANBgkqhkiG9w0BAQsF
    ADAvMS0wKwYDVQQDEyRNZWRJbXBhY3QgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkwHhcNMjUwMzMxMTYxNjM5WhcNMzIwMzMxMTYyNjM5WjBLMRMwEQYKCZImiZPy
    LGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJbWVkaW1wYWN0MRkwFwYDVQQDExBN
    ZWRpbXBhY3QtU3ViQ0EyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    pFr1NsAGVwv3WTbJu8jSwcX7FGkWLfi+ZDQf/MkhfZ5wpktfC/Kn+xF2i7rPWroG
    RhKl0OPJbB1ciibeQpreKKPl/w+2dpm1z/oUFjJCbb1vyvivJnqvdEpHPNfido31
    SyzvM2Lnew87w5iFeGAZTTQWTo+HFm33u3XPfmyBv7ghjgI1ImtLV6/gqNfd+NIV
    1Lk0He3wjAtpD8yf++oO+zVjEYqWAOKBqxHWdsSiGI6rXTP+6wZttfCBWcDzfHQ+
    DUjhDwol+JUYFoaOqHYsMs5tVdeO1KYjtURh7Ci4ffI/o7uGlp8bRlVutRQdbgb1
    B4qZC3GlYDrRMlu2glrWgwIDAQABo4ICazCCAmcwEAYJKwYBBAGCNxUBBAMCAQEw
    IwYJKwYBBAGCNxUCBBYEFMW8QNnCp76D9jfeq2nzdbpqQlesMB0GA1UdDgQWBBRC
    YnvyID3DiIFId3NHLuIdKFWzjTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
    BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTvtQvVxg1U
    hOCfZpsJ5k+jmIedyDBjBgNVHR8EXDBaMFigVqBUhlJodHRwOi8vY3JsLm1lZGlt
    cGFjdC5jb20vQ2VydEVucm9sbC9NZWRJbXBhY3QlMjBSb290JTIwQ2VydGlmaWNh
    dGUlMjBBdXRob3JpdHkuY3JsMIIBTgYIKwYBBQUHAQEEggFAMIIBPDCBywYIKwYB
    BQUHMAKGgb5sZGFwOi8vL0NOPU1lZEltcGFjdCUyMFJvb3QlMjBDZXJ0aWZpY2F0
    ZSUyMEF1dGhvcml0eSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMs
    Q049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1NZWRpbXBhY3QsREM9Y29t
    P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
    aG9yaXR5MGwGCCsGAQUFBzABhmBodHRwOi8vY3JsLm1lZGltcGFjdC5jb20vQ2Vy
    dEVucm9sbC9wdjFtZWRvY2ExX01lZEltcGFjdCUyMFJvb3QlMjBDZXJ0aWZpY2F0
    ZSUyMEF1dGhvcml0eSgyKS5jcnQwDQYJKoZIhvcNAQELBQADggIBAGg+hxANOn77
    WVjqTNgq03fFUNDmPPd9yRZlPiqTsAZHLlXZP3I7uxTVH81tdYXGUN6YVtcEWjjY
    COrfBCuZJG1zadDnW0JWruWGsCPuHJMMUlNoQI2kivbQJ+Oy1V0c/dnSVMFMYeYT
    NO4Ux+OP3yPNGqppUA6NgTn/8a2O78Q4RIdFyKUjmAvk+T3OkwlyxzH0HRmm1EuG
    TpciKs4r2QJJwM+XgiVm+szlJwnSXLZ+ulTkmMDObQbrQv8AOvvwCzpCDnXswsdQ
    TqMLi+b21Gp0Ey26x+4eF//0PuIa/GY8bwVPm0en5s0VNOiZV1tJ3olWvEuFsMFW
    ZIJrIbifWLbJyLhibFoVOjqGI7WfgSG5Y97symgpZkYhQbCEYbejbTPKVt9YfrbM
    3r0RBYqJxdFdEUmbcGD8ABio0fIdDWGcvDqohi6U6w40+6PcV4BGp/z00QdAY1pq
    mKgUpmxla8mo99hNCzTaBFnAxJmxsQPeYtg+bst4WAfFjH4wb7x6AWREXDmnBjhP
    54DWCtMpCmQP4I+PUU7BBh0ggej1bz4xBZkc+h5/RgjfnoyCdnXqb4cadyxjm2oR
    WclQ8gvf9Ksgp3gZhkNCkkcOEpJK0Sajl67WRymJMSCqTW1ABRq/dF9x+ZEv47jz
    smxqtuj4gH7EmlJW+6/Kc4YIH2ghrx0C
    -----END CERTIFICATE-----
  medimpact-root-2045.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFXjCCA0agAwIBAgIQRy9w95r4CaJHlau8jkFw6jANBgkqhkiG9w0BAQsFADAv
    MS0wKwYDVQQDEyRNZWRJbXBhY3QgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkw
    HhcNMTMxMDIxMjIwMjUwWhcNNDUwMzMxMTU1MTMzWjAvMS0wKwYDVQQDEyRNZWRJ
    bXBhY3QgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQDWu57UB9VLHU6CoW/KNaVI7q0K9BuZiEAkoJyRpONE
    IXcZTJ35/1n7H9V2db/Gu4T+cae8C9l+81lhCp29GHh2l7/CwV91UCqrm8SD8VuL
    NpA03Q26FnT7RgZDTbe9QO25GUS5+Gqm2zr6jpwXyw1I7ooa8c3f6Olr6BgDGieV
    QqA4z6PCMVor+FQFP1SqRlTzewyj22pRH8xqZc1HBptw1xgKYGlZXudSQcErICW9
    fnewPnhroTHN2f5Gd8qiR6bfXW0NrxPaZO3AhtKIn0stWRbHGrYaAWB1QsW7Dtrz
    hGHwCQkRJEyi+ptMXIWRanGOtGe61MTdvcOfObDsJIzhfO8gkpYtM5lRNKAk2QMV
    9gzY9QGG08W2yisa7uVe7UsBP2aM5IE86jqtTwBkZ6fStD59gKTVHWjvPLjBad2/
    45NFm1JNEbu3XfNcmQt/xqhZRWkMfqVhEf5zWbD2mzhw4usohq/uaUp1qTd075A7
    vI8ZK8SOnK4WKy9sRmIhzKwt2ZMpEbcAPyHX4d1aS35MousHHehDToXIlut8RsBH
    Jf03GlKniXq1Lg5VIiS2ZNhAmFAa1zp8PPoge4zd6dpt6hEaHUOMtlsFdF+OEPGm
    tFXqRabKzGFyG8etEKhA+BVi/fzq8QpQwA1zf949O9Z1KG2XzZLV3mqhh2jWzJnf
    wQIDAQABo3YwdDALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4E
    FgQU77UL1cYNVITgn2abCeZPo5iHncgwEAYJKwYBBAGCNxUBBAMCAQIwIwYJKwYB
    BAGCNxUCBBYEFPoK+PXa16WLSBob+XmkFh1kxoZuMA0GCSqGSIb3DQEBCwUAA4IC
    AQB1EOb/1K4L4SYfKYxJ6HCaEUGtIVQB4wdDAfY8pwnCajPbVafPMjn1SBKGYpGn
    2RdekBbd/VKLzI6EI+YBBuA6xVd6zgE40jzvFMwRFBqG5ZrAl1s62T4SmiFhgXdX
    m7pfE7O9DP6zWKepQND2PXjtcSaIbuZa/OpP7RhNOURtLP8aumA3AFSz3ePniRef
    tg/Zqt9ydr7YbFR1Vm/sMHhBT+Nh+1b7MNxDoVtMbgIdhn2Efa3isa4nvc8i2Ocw
    xNs2yIf4dL1kZqDj0F0JGznNIZus1oIPgQ8wDgJvgir3ZWrZIGgz/xa+ZzQQC08m
    gklW0s3GfBiu5Nz3Vpw3+NeihuglPBR4qhS5b7PYS1U1C/Hn6rLx2UB+Zzba6UNm
    sxlNOxQoVzsvw2dgYf5WS7uJqjMgkUnrBncYlykkdqR+AtynNXQWgJlJkud1X2R1
    M9caBx3QWgOVa2RI+KiQGcI/xcFNluq3lJL2fsZCncW7rDxDQ4DLJBCdI8RavZpi
    iZ4aLC3Bl1G+P8tz4Dba9bbOhJjvTF857Zp/2o15u5yRzSMYoUzoxup45UGCE0LV
    oZIVIWdAy0WVGCnLy1ComFsxJymbl+2jZIoyOMXdnuqOk0v+zgm/wJ5b1IdZFGxG
    2Vn9y7IwPiMIshtBqyrmeNfoGoEKAY9oIoGozuG5QiCDmw==
    -----END CERTIFICATE-----
# ---
# apiVersion: v1
# kind: Secret
# metadata:
  # name: install-mi-cacerts
  # namespace: kube-system
# type: Opaque
# stringData:
  # setup.sh: |
    # echo "$MEDIMPACT_INTERMEDIATE_1" > /usr/local/share/ca-certificates/medimpact-intermediate-1.crt && echo "$MEDIMPACT_INTERMEDIATE_2" > /usr/local/share/ca-certificates/medimpact-intermediate-2.crt && echo "$MEDIMPACT_SUBCA1_2019" > /usr/local/share/ca-certificates/medimpact-subca1-2019.crt && echo "$MEDIMPACT_SUBCA2_2019" > /usr/local/share/ca-certificates/medimpact-subca2-2019.crt && echo "$MEDIMPACT_ROOT" > /usr/local/share/ca-certificates/medimpact-root.crt && update-ca-certificates && systemctl restart containerd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: install-mi-cacerts
  labels:
    app: install-mi-cacerts
spec:
  selector:
    matchLabels:
      app: install-mi-cacerts
  template:
    metadata:
      labels:
        app: install-mi-cacerts
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Exists"
        effect: "NoSchedule"
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        # args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "systemctl restart containerd"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "sleep 10; $(SETUP_SCRIPT)"]
        image: medusw2prd001.azurecr.io/dockerhub/debian:bullseye
        imagePullPolicy: IfNotPresent
        env:
        - name: MEDIMPACT_SUBCA1_2032
          valueFrom:
            secretKeyRef:
              name: install-mi-cacerts
              key: medimpact-subca1-2032.crt
        - name: MEDIMPACT_SUBCA2_2032
          valueFrom:
            secretKeyRef:
              name: install-mi-cacerts
              key: medimpact-subca2-2032.crt
        - name: MEDIMPACT_ROOT_2045
          valueFrom:
            secretKeyRef:
              name: install-mi-cacerts
              key: medimpact-root-2045.crt
        - name: SETUP_SCRIPT
          valueFrom:
            secretKeyRef:
              name: install-mi-cacerts
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1