# User folders must be entered here
bases:
- ./aboppana
- ./aganapathi
- ./amula
- ./aoluoch
- ./athomas
- ./avishnevskiy
- ./cgroeneveld
- ./csam
- ./cspain
- ./ctagariello
- ./dandrews
- ./egoepfert
- ./hpunjani
- ./imaund
- ./hlee
- ./jouyang
- ./kmungekar
- ./lbarros
- ./markd
- ./mcallagy
- ./mdeckert
- ./mpepa
- ./nbaldwin
- ./norman
- ./ngiri
- ./nsanyasi
- ./pdey
- ./rgudipati
- ./rkulangarathodi
- ./rsethi
- ./ryeggdi
- ./sdhuri
- ./thnguyen
- ./vkancherla
