apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: confluence-postgres
  name: confluence-postgres
  namespace: itapps-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence-postgres
  template:
    metadata:
      labels:
        app: confluence-postgres
    spec:
      containers:
        - name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/db-files/
            - name: POSTGRES_DB
              value: confluence
            - name:  POSTGRES_PASSWORD
              value: goodpassword
            - name:  POSTGRES_USER
              value: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "1000m"
              memory: "1000Mi"
            requests:
              cpu: "100m"
              memory: "150Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            # - mountPath: /var/lib/postgresql/certs/
              # name: certs
      securityContext:
        runAsUser: 70
      volumes:
        - name: data
          emptyDir: {}
        # - name: certs
          # secret:
            # defaultMode: 0600
            # secretName: confluence-postgres-certs
            # items:
            # - key: server.key
              # path: server.key
            # - key: server.crt
              # path: server.crt
