---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: confluence
  name: confluence
  namespace: itapps-dev
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: confluence
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
      # - image: atlassian/confluence:latest
      - image: docker-local.artifactory.medimpact.com/itapps/confluence:latest
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: confluence
        # command:
        # - /bin/sh
        # - -c
        # - while [ true ]; do sleep 10; done
        env:
        - name: ATL_JDBC_URL
          # value: "jdbc:oracle:thin:@//dp1medex1-scan1:2025/T1CFL"
          value: "jdbc:postgresql://confluence-postgres:5432/confluence"
        - name: ATL_JDBC_USER
          value: postgres
          # value: postgres
        - name: ATL_JDBC_PASSWORD
          value: goodpassword
          # value: goodpassword
        - name: ATL_DB_TYPE
          # value: oracle
          value: postgresql
        - name: ATL_PROXY_NAME
          value: confluence-dev.medimpact.com
        - name: ATL_PROXY_PORT
          value: "443"
        - name: ATL_TOMCAT_ACCESS_LOG
          value: "false"
        # - name: ATL_LUCENE_INDEX_DIR
          # value: "/lucene"
        - name: CONFLUENCE_SHARED_HOME
          value: "/var/atlassian/application-data/confluence"
        - name: CONFLUENCE_LOG_STDOUT
          value: "true"
        - name: JVM_MINIMUM_MEMORY
          value: "1024m"
        - name: JVM_MAXIMUM_MEMORY
          value: "4096m"
        - name: ATL_LICENSE_KEY
          value: "AAABrg0ODAoPeNp9klFv2jAUhd/9KyztZdMW6oQNGJKlQZKWdCG0hNIJ8eI6l8YicSLbCcm/XwggdS97vL5XOuc7x582FeDHSmLHxjaZkp9TZ4Rdb4Md4jjoCO0WlBaFpPaIkDGZDIc2iqr8DdTq8KK7HXUIIcgtpGHcRCwHmrAaBkwmCk76Vw6JyMtuNeBFjnghD4NuEDVQoypAT5XiKdPgMQP0LGmRoWV/R6HgIDX4TSlU2y8rmYlcGEhuWv6Siex/YjGoGlTg0fmzE1h/SOxZ4cuOWOuHVxtlF4EF0ylduif3fiaXzbZN1/7bnTvZvd77u+cjaVoxW2SzdC3L5NhED9HXsSofG56tf0/md+W7mvPTnu4p6rxIA5JJ/tFzBzS8AvXksWHKgKIHlmm4MXYGw8CL/cgK7YlDfgxHY9RN9N+XlXpnUmhmzl0sIQl6TrwAlpmUMwU4brWBXH/DgeQD5Crobz8EO7K6RnsfV+VNW0LfmOdv/XD15K9vsdxKd5AHmitR9rJd8Iesgo4Rf76E+wWf28f9R9hPsQc1ZEUJCl8VkF+zrLqYvkD/BXLDz4EwLAIUV9X2bctKhrvkv4PI3v8yHebP3RACFAUUN5lPeJL57KSPbLc1xb1Y9qf6X02kk"
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 10
        livenessProbe:
          httpGet:
            path: /status
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 300
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2000m"
            memory: "6144Mi"
          requests:
            cpu: "100m"
            memory: "2000Mi"
        volumeMounts:
        - name: data
          mountPath: /var/atlassian/application-data/confluence
        - name: lucene
          mountPath: /var/atlassian/application-data/confluence/index
      securityContext:
        runAsUser: 2002
        fsGroup: 2002
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
      - name: data
        # emptyDir: {}
        persistentVolumeClaim:
          claimName: itapps-confluence-dev
      - name: lucene
        emptyDir: {}