---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: RELEASE-NAME-confluence
  labels:
    app: confluence
spec:
  replicas: 1
  serviceName: RELEASE-NAME-confluence
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      serviceAccountName: RELEASE-NAME-confluence
      terminationGracePeriodSeconds: 25
      securityContext:
        fsGroup: 2002
      containers:
        - name: confluence
          image: "docker-local.artifactory.medimpact.com/itapps/confluence:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - name: hazelcast
              containerPort: 5701
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8090
              path: /status
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "2"
              memory: 2G
          volumeMounts:
            - name: local-home
              mountPath: "/var/atlassian/application-data/confluence"
            - name: local-home
              mountPath: "/opt/atlassian/confluence/logs"
              subPath: "logs"
            - name: shared-home
              mountPath: "/var/atlassian/application-data/shared-home"
          env:
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
            - name: ATL_TOMCAT_PORT
              value: "8090"
            - name: ATL_TOMCAT_ACCESS_LOG
              value: "true"
            - name: UMASK
              value: "0022"
            - name: SET_PERMISSIONS
              value: "true"
            - name: ATL_PRODUCT_HOME_SHARED
              value: "/var/atlassian/application-data/shared-home"
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              valueFrom:
                configMapKeyRef:
                  key: additional_jvm_args
                  name: RELEASE-NAME-confluence-jvm-config
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HAZELCAST_KUBERNETES_SERVICE_NAME
              value: "RELEASE-NAME-confluence"
            - name: ATL_CLUSTER_TYPE
              value: "kubernetes"
            - name: ATL_CLUSTER_NAME
              value: "RELEASE-NAME-confluence"
            - name: ATL_DB_TYPE
              value: "postgresql"
            - name: ATL_JDBC_URL
              value: "jdbc:postgresql://confluence-postgres:5432/confluence"
            - name: ATL_JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: confluence-creds
                  key: username
            - name: ATL_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: confluence-creds
                  key: password
            - name: ATL_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: confluence-license
                  key: license-key
            - name: JVM_MINIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: min_heap
                  name: RELEASE-NAME-confluence-jvm-config
            - name: JVM_MAXIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: max_heap
                  name: RELEASE-NAME-confluence-jvm-config
            - name: JVM_RESERVED_CODE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: reserved_code_cache
                  name: RELEASE-NAME-confluence-jvm-config
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "/shutdown-wait.sh"]
      volumes:
        - name: local-home
          emptyDir: {}
        - name: shared-home
          persistentVolumeClaim:
            claimName: sharedvol