# Default values for Gravitee.io Designer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
chaos:
  enabled: false

mongo:
  uri: mongodb://dv1medgravpoc1.medimpact.com:27017,dv1medgravpoc2.medimpact.com:27017,dv1medgravpoc3.medimpact.com:27017/gravitee-designer?&connectTimeoutMS=30000&replicaSet=rs0&retryWrites=true&w=majority

mongodb-replicaset:
  enabled: false

apim:
  console:
    url: https://grav-dev-ui.medimpact.com
  management:
    url: https://grav-dev-api.medimpact.com/management
    cookie:
      domain: .medimpact.com
      name: Auth-Graviteeio-APIM

api:
  enabled: true
  name: designer-api
  restartPolicy: OnFailure
  reloadOnConfigChange: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicaCount: 3
  image:
    repository: graviteeio/designer-api
    # tag: 1.0.0
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - name: gravitee_secrets
  # env:
  #   - name: ENV_VARIABLE
  #     value: "some value"
  service:
    type: ClusterIP
    externalPort: 83
    internalPort: 3001
  # annotations:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 4
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  ingress:
    enabled: true
    path: /api
    # Used to create an Ingress record.
    hosts:
      - grav-dev-design.medimpact.com
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      # kubernetes.io/tls-acme: "true"
    #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
    tls:
      - hosts:
          - grav-dev-design.medimpact.com
        # secretName: api-custom-cert
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
    #  lifecycle:
    #    postStart: '[ "/bin/sh", "-c", "echo Post starting Gravitee Designer API" ]'
    #    preStop: '[ "/bin/sh", "-c", "echo Pre stopping Gravitee Designer API" ]'
    ## Additional gravitee API volume mounts
    # Defines additional volume mounts.
    # extraVolumeMounts: |
    # - name: extra-volume
    #   mountPath: /mnt/volume
    #   readOnly: true
    #   existingClaim: volume-claim

ui:
  enabled: true
  name: designer-ui
  replicaCount: 3
  image:
    repository: graviteeio/designer-ui
    # tag: 1.0.0
    pullPolicy: IfNotPresent
  # pullSecrets:
  #   - name: gravitee_secrets
  # env:
  #   - name: ENV_VARIABLE
  #     value: "some value"
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 4
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  service:
    name: nginx
    type: ClusterIP
    externalPort: 8002
    internalPort: 8080
    # annotations:
  ingress:
    enabled: true
    path: /
    # Used to create an Ingress record.
    hosts:
      - grav-dev-design.medimpact.com
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/app-root: /
      # kubernetes.io/rewrite-target: /
      ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\n"
      #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
    tls:
      - hosts:
          - grav-dev-design.medimpact.com
        # secretName: api-custom-cert
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
    #  lifecycle:
    #    postStart: '[ "/bin/sh", "-c", "echo Post starting Gravitee Designer UI" ]'
    #    preStop: '[ "/bin/sh", "-c", "echo Pre stopping Gravitee Designer UI" ]'
    ## Additional gravitee ui volume mounts
    # Defines additional volume mounts.
    # extraVolumeMounts: |
    # - name: extra-volume
    #   mountPath: /mnt/volume
    #   readOnly: true

generator:
  enabled: true
  name: designer-generator
  restartPolicy: OnFailure
  reloadOnConfigChange: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicaCount: 3
  image:
    repository: graviteeio/designer-generator
    # tag: 1.0.0
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - name: gravitee_secrets
  # env:
  #   - name: ENV_VARIABLE
  #     value: "some value"
  service:
    type: ClusterIP
    externalPort: 84
    internalPort: 3003
  # annotations:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 4
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
    #  lifecycle:
    #    postStart: '[ "/bin/sh", "-c", "echo Post starting Gravitee Designer Generator" ]'
    #    preStop: '[ "/bin/sh", "-c", "echo Pre stopping Gravitee Designer Generator" ]'
    ## Additional gravitee API volume mounts
    # Defines additional volume mounts.
    # extraVolumeMounts: |
    # - name: extra-volume
    #   mountPath: /mnt/volume
    #   readOnly: true
    #   existingClaim: volume-claim