# User folders must be entered here
bases:
- ./aboppana
- ./aganapathi
- ./ahoang
- ./ajsingh
- ./amula
- ./anomula
- ./athomas
- ./cgroeneveld
- ./cmcvey
- ./dandrews
- ./dzeng
- ./egoepfert
- ./eramisetti
- ./etruong
- ./fdirlikli
- ./fgreen
- ./hpunjani
- ./imaund
- ./imiranda
- ./jherzig
- ./jothompson
- ./jouyang
- ./jsimko
- ./kmungekar
- ./markd
- ./mcallagy
- ./mdeckert
- ./nbaldwin
- ./ngiri
- ./rsethi
- ./scoughlan
- ./ssecker
- ./tdas
- ./thoffman
- ./yvichare
