{
 "title": "Executive Summary",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_info{node=~\".*no[0-9]+.*\",cluster=~\"$cluster\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "vCPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "$cluster cluster capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_info{node=~\".*no[0-9]+.*\",cluster=~\"$cluster\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
       "legendFormat": "Pods"
      }
     ]
    },
    {
     "title": "vCPUs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster cluster capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_info{node=~\".*no[0-9]+.*\",cluster=~\"$cluster\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
       "legendFormat": "Pods"
      }
     ]
    },
    {
     "title": "vCPUs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster cluster capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_info{node=~\".*no[0-9]+.*\",cluster=~\"$cluster\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
       "legendFormat": "Pods"
      }
     ]
    },
    {
     "title": "vCPUs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster cluster capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_info{node=~\".*no[0-9]+.*\",cluster=~\"$cluster\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
       "legendFormat": "Pods"
      }
     ]
    },
    {
     "title": "vCPUs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster cluster capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_info{node=~\".*no[0-9]+.*\",cluster=~\"$cluster\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
       "legendFormat": "Pods"
      }
     ]
    },
    {
     "title": "vCPUs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  }
 ]
}