{
 "title": "Default Kubernetes Overview",
 "tags": [ "default overview" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Master CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(sort_desc(max(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}[2m])) by (instance))))",
     "legendFormat": "Top current"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}[2m])) by (instance))",
     "legendFormat": "Avg current"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(sort_desc(max(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}[2m])) by (instance))))",
     "legendFormat": "Top current"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}[2m])) by (instance))",
     "legendFormat": "Avg current"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}) / sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}) / sum(node:node_num_cpu:sum{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Top Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\",cluster=~\"$cluster\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Top CPU Containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",cluster=~\"$cluster\"}[2m])) by (pod, container, cluster))",
     "legendFormat": "{{ container }} in {{ pod }}"
    }
   ]
  },
  {
   "title": "Master Memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(1-(node_memory_MemAvailable_bytes{instance=~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}/node_memory_MemTotal_bytes{instance=~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}))",
     "legendFormat": "Top current"
    },
    {
     "expr": "avg(1-(node_memory_MemAvailable_bytes{instance=~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}/node_memory_MemTotal_bytes{instance=~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}))",
     "legendFormat": "Avg current"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(1-(node_memory_MemAvailable_bytes{instance!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}/node_memory_MemTotal_bytes{instance!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}))",
     "legendFormat": "Top current"
    },
    {
     "expr": "avg(1-(node_memory_MemAvailable_bytes{instance!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}/node_memory_MemTotal_bytes{instance!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}))",
     "legendFormat": "Avg current"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}) / sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"}) / sum(node_memory_MemTotal_bytes{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"})",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Most Throttled Containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, (sum(increase(container_cpu_cfs_throttled_periods_total{image!=\"\",container!=\"POD\",pod!~\"node-exporter.*\",cluster=~\"$cluster\"}[2m])) by (pod, container, cluster)) /sum(increase(container_cpu_cfs_periods_total{image!=\"\",container!=\"POD\",pod!~\"node-exporter.*\",cluster=~\"$cluster\"}[2m])) by (pod, container, cluster))",
     "legendFormat": "{{ container }} in {{ pod }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_status_phase{phase!=\"\",cluster=~\"$cluster\"}) - 28)/ count(kube_node_info{node!~\".*ma[0-9]+.*\",cluster=~\"$cluster\"})",
     "legendFormat": "Pods per node"
    }
   ]
  },
  {
   "title": "Pods Restarting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod, cluster)(delta(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[$__range]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 2, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace, cluster)(delta(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[1m]) > 0)",
     "legendFormat": "{{pod}} in {{namespace}}"
    }
   ]
  },
  {
   "title": "Most restarts",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "topk(1, kube_pod_container_status_restarts_total{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Top Memory Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",cluster=~\"$cluster\"}) by (pod, cluster))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase!=\"Running\",cluster=~\"$cluster\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role !~ \".*ma[0-9]+.*\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Newest Pods",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "bottomk(60, sort(time() - kube_pod_status_scheduled_time{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Top Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum by (instance, cluster) (irate(node_network_receive_bytes_total{cluster=~\"$cluster\"}[4m]))))",
     "legendFormat": "RX: {{ instance }}"
    },
    {
     "expr": "topk(5, sort_desc(sum by (instance, cluster) (irate(node_network_transmit_bytes_total{cluster=~\"$cluster\"}[4m]))))",
     "legendFormat": "TX: {{ instance }}"
    }
   ]
  }
 ]
}