{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance:",
    "query": {
     "query": "label_values(up{job=\"vault\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(up{job=\"vault\",instance=~\"$node:(.*)\"}, instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": {
     "query": "label_values(vault_secret_lease_creation, mount_point)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_core_active{instance=\"$node:$port\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "avg without(instance, host) (vault_secret_kv_count{instance=\"$node:$port\"})",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Lease expiration errors in last 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vault_expire_lease_expiration_error{instance=\"$node:$port\"}[24h])"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance, host) (vault_identity_entity_alias_count{instance=\"$node:$port\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{instance=\"$node:$port\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{instance=\"$node:$port\"})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Operations by Method and Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(vault_route_method__count{method!=\"rollback\", method!=\"list\", instance=\"$node:$port\"}[1m]))",
     "legendFormat": "{{ method }} | {{ engine }} "
    }
   ]
  },
  {
   "title": "Time of Operations by Method and Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "µs", "label": "Time of one operation" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_route_method__sum{method!=\"rollback\", method!=\"list\", instance=\"$node:$port\"}[1m]) / rate(vault_route_method__count{method!=\"rollback\", method!=\"list\", instance=\"$node:$port\"}[1m]) * 1000) by (method, engine) ",
     "legendFormat": "{{method }} | {{ engine }}"
    }
   ]
  },
  {
   "title": "Lease creation by mount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(vault_secret_lease_creation{instance=\"$node:$port\"}[5m])",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Leases by TTL (Coming soon)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "{{ creation_ttl }}" }
   ]
  },
  { "title": "CPU/Mem Info: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{instance=\"$node:$port\"} / vault_runtime_malloc_count{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{instance=\"$node:$port\"})",
     "legendFormat": "$node"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_count{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy{instance=\"$node:$port\"})",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count{instance=\"$node:$port\"} - vault_token_store_count{instance=\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl{instance=\"$node:$port\"})",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth{instance=\"$node:$port\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation{instance=\"$node:$port\"})",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count{instance=\"$node:$port\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count{instance=\"$node:$port\"})",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Lookups per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Consul Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_consul_get_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(irate(vault_consul_put_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(irate(vault_consul_delete_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "irate(vault_consul_list_count{instance=\"$node:$port\"}[1m])",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count{instance=\"$node:$port\"}[1m]))",
     "legendFormat": "GET"
    }
   ]
  }
 ]
}