apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
type: Opaque
stringData:
  auth: consume:$apr1$B7Ak1icx$KhXLEBuOPoYkZT8t5cfJv0
  #IdNFZzvJn7M4VMW8DQzk
  #^((?!prometheus).)*$