apiVersion: v1
kind: Secret
metadata:
  name: prometheus-remotewrite-victoriametrics
  namespace: monitoring
type: Opaque
stringData:
  username: consume
  password: IdNFZzvJn7M4VMW8DQzk
  #hashed format: consume:$apr1$B7Ak1icx$KhXLEBuOPoYkZT8t5cfJv0