---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://argocd-dev.medimpact.com
  exec.enabled: "true"
  statusbadge.enabled: "true"
  accounts.jenkins: apiKey
  accounts.jenkins.enabled: "true"
  oidc.config: |
    name: MedImpact
    issuer: https://sts.medimpact.com/adfs
    clientID: 202f6f5e-291b-478a-a2f4-3ce120a32c48
    clientSecret: fJGj_k3Czj0l2B2Mdg7F0Y7qQyAZ33_wq5oLmnx5
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  resource.inclusions: |
    - apiGroups:
      - "*"
      kinds:
      - Deployment
      - StatefulSet
      - CronJob
      - Job
      - ReplicaSet
      - Pod
      - Endpoints
      - EndpointSlice
      - ConfigMap
      - Secret
      - Service
      - Ingress
      - NetworkPolicy
      - HorizontalPodAutoscaler
      - PodDisruptionBudget
      - PersistentVolumeClaim
      - Event
      clusters:
      - "*"