apiVersion: v1
kind: Service
metadata:
  name: pg3-parules-headless
  namespace: pas-dev
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: pg3-parules