---
# Role for mms-default service account to manage jobs and pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ncpdp-coordinator-role
  namespace: mms-qa
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
# RoleBinding to associate the above Role with mms-default ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ncpdp-coordinator-rolebinding
  namespace: mms-qa
subjects:
  - kind: ServiceAccount
    name: mms-default
    namespace: mms-qa
roleRef:
  kind: Role
  name: ncpdp-coordinator-role
  apiGroup: rbac.authorization.k8s.io

