---
# Source: designer/templates/api/api-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grav-designer-designer-api
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-api"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
data:
  env.props: |
    ############## APIGROW MAIN CONFIGURATION ############## 
    APIZR_API_KEY=ZQvoqSZtRrueflUhqAXK
    APIZR_API_KEY_HEADER_NAME=x-apizr-apikey
    AUTOSWAGGER_FRONT_URL=grav-dev-design.medimpact.com
    COOKIE_DOMAIN=.medimpact.com

    ############ JWT SECTION ###############
    JWT_COOKIE_NAME=apizr-login-cookie
    JWT_SECRET=45890GJKDLZEEF567890
    
    ############ SWAGGER PRODUCER SECTION ###############
    SWAGGER_PRODUCER_URL=http://grav-designer-designer-generator:84
    SWAGGER_PRODUCER_APIKEY=PgUfDekIFAYmanUeRIQU
    
    ############# Gravitee configuration ################
    GRAVITEE_ENABLED=true
    GRAVITEE_MANAGEMENT_API_URL=https://grav-dev-api.medimpact.com/management
    GRAVITEE_COOKIE_NAME=Auth-Graviteeio-APIM
    GRAVITEE_ORGANIZATION=DEFAULT
    GRAVITEE_ENVIRONMENT=DEFAULT

    MONGO_URI=mongodb://dv1medgravpoc1.medimpact.com:27017,dv1medgravpoc2.medimpact.com:27017,dv1medgravpoc3.medimpact.com:27017/gravitee-designer?&connectTimeoutMS=30000&replicaSet=rs0&retryWrites=true&w=majority
    HOST=0.0.0.0
---
# Source: designer/templates/generator/generator-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grav-designer-designer-generator
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-generator"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
data:
  env.props: |
    HOST=0.0.0.0
    PORT=3003
---
# Source: designer/templates/ui/ui-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grav-designer-designer-ui
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-ui"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
data:
  use-gzip: "true"
  gzip-level: "5"
  gzip-types: "*"
  constants.json: |
    {
      "API_URL": "https://grav-dev-design.medimpact.com/api",
      "GRAVITEE_ENABLED": true,
      "GRAVITEE_MANAGEMENT_UI_URL": "https://grav-dev-ui.medimpact.com"
    }
---
# Source: designer/templates/api/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grav-designer-designer-api
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-api"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
  annotations:
spec:
  type: "ClusterIP"
  ports:
    - port: 83
      targetPort: 3001
      protocol: TCP
      name: designer-api
  selector:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/component: "designer-api"
---
# Source: designer/templates/generator/generator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grav-designer-designer-generator
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-generator"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
  annotations:
spec:
  type: "ClusterIP"
  ports:
    - port: 84
      targetPort: 3003
      protocol: TCP
      name: designer-generator
  selector:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/component: "designer-generator"
---
# Source: designer/templates/ui/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grav-designer-designer-ui
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-ui"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
  annotations:
spec:
  type: "ClusterIP"
  ports:
    - port: 8002
      targetPort: 8080
      protocol: TCP
      name: designer-ui
  selector:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/component: "designer-ui"
---
# Source: designer/templates/api/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grav-designer-designer-api
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-api"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: designer
      app.kubernetes.io/instance: grav-designer
      app.kubernetes.io/component: "designer-api"
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "false"
        checksum/config: f9fc52a0c40fc9ff66bb2376657a84667129d65d75784ede7c807c8cbefe2bc1
      labels:
        app.kubernetes.io/name: designer
        app.kubernetes.io/instance: grav-designer
        app.kubernetes.io/component: "designer-api"
    spec:
      containers:
        - name: grav-designer-designer-api
          image: "graviteeio/designer-api:1.0.0"
          imagePullPolicy: IfNotPresent
          securityContext:  
            runAsUser: 1001
            runAsNonRoot: true
          ports:
            - containerPort: 3001
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /app/.env
              subPath: env.props
      volumes:
        - name: config
          configMap:
            name: grav-designer-designer-api
---
# Source: designer/templates/generator/generator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grav-designer-designer-generator
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-generator"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: designer
      app.kubernetes.io/instance: grav-designer
      app.kubernetes.io/component: "designer-generator"
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "false"
        checksum/config: 35f39eae6425a60f6adaf3b3b381ef6d1d69aa7975b47d153f0cc510eb2f5639
      labels:
        app.kubernetes.io/name: designer
        app.kubernetes.io/instance: grav-designer
        app.kubernetes.io/component: "designer-generator"
    spec:
      containers:
        - name: grav-designer-designer-generator
          image: "graviteeio/designer-generator:1.0.0"
          imagePullPolicy: IfNotPresent
          securityContext:  
            runAsUser: 1001
            runAsNonRoot: true
          ports:
            - containerPort: 3003
          env:
            - name: HOST
              value: 0.0.0.0
            - name: APIZR_API_KEY_VALUE
              value: PgUfDekIFAYmanUeRIQU
          livenessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /app/.env
              subPath: env.props
      volumes:
        - name: config
          configMap:
            name: grav-designer-designer-generator
---
# Source: designer/templates/ui/ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grav-designer-designer-ui
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-ui"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: designer
      app.kubernetes.io/instance: grav-designer
      app.kubernetes.io/component: "designer-ui"
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "false"
        checksum/config: 76034e3002162d3e6f66843c38e12605502fd66eed12fb779f68609b572f29d7
      labels:
        app.kubernetes.io/name: designer
        app.kubernetes.io/instance: grav-designer
        app.kubernetes.io/component: "designer-ui"
    spec:
      containers:
        - name: grav-designer-designer-ui
          image: "graviteeio/designer-ui:1.0.0"
          imagePullPolicy: IfNotPresent
          securityContext:  
            runAsUser: 1001
            runAsNonRoot: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/constants.json
              subPath: constants.json
      volumes:
        - name: config
          configMap:
            name: grav-designer-designer-ui
---
# Source: designer/templates/api/api-autoscaler.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: grav-designer-designer-api
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-api"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grav-designer-designer-api
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
---
# Source: designer/templates/generator/generator-autoscaler.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: grav-designer-designer-generator
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-generator"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grav-designer-designer-generator
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
---
# Source: designer/templates/ui/ui-autoscaler.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: grav-designer-designer-ui
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-ui"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grav-designer-designer-ui
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
---
# Source: designer/templates/api/api-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grav-designer-designer-api
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-api"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
  annotations:
      ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  rules:
    - host: grav-dev-design.medimpact.com
      http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: grav-designer-designer-api
              servicePort: 83
  tls:
    - hosts:
      - grav-dev-design.medimpact.com
---
# Source: designer/templates/ui/ui-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grav-designer-designer-ui
  labels:
    app.kubernetes.io/name: designer
    app.kubernetes.io/instance: grav-designer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: "designer-ui"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: designer-1.0.1
  annotations:
      ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\n"
      kubernetes.io/app-root: "/"
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: grav-dev-design.medimpact.com
      http:
        paths:
          - path: /
            backend:
              serviceName: grav-designer-designer-ui
              servicePort: 8002
  tls:
    - hosts:
      - grav-dev-design.medimpact.com
