---
# Create ClusterRole for privileged PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:privileged
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
# Create ClusterRoleBinding for privileged PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
---
# Create RoleBinding for kube-proxy just in kube-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:kube-proxy
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: kube-proxy
    namespace: kube-system
# ---
# # Create RoleBinding for kube-router just in kube-system namespace
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
  # name: psp:kube-router
  # namespace: kube-system
  # labels:
    # addonmanager.kubernetes.io/mode: Reconcile
    # kubernetes.io/cluster-service: "true"
# roleRef:
  # apiGroup: rbac.authorization.k8s.io
  # kind: ClusterRole
  # name: psp:privileged
# subjects:
  # - kind: ServiceAccount
    # name: kube-router
    # namespace: kube-system
---
# Create RoleBinding for calico just in kube-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:calico
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: calico-node
    namespace: kube-system