apiVersion: v1
metadata:
  name: minio-prometheus
  namespace: itsystems-lab
kind: ConfigMap
data:
  prom.yaml: |
    global:
       scrape_interval: 15s
    
    scrape_configs:
       - job_name: minio-job
         bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MDc3MTM5NTIsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJtYXJrIn0.w5HK44lW4wqsCu94tYfntGYTJ6THww3FVx5_MLISYxQaLMczpXQ7cLakLMmHem1Rr_cY8PSsn4bGbEH4UEVUcg
         metrics_path: /minio/v2/metrics/cluster
         scheme: https
         static_configs:
         - targets: [s3-lab.medimpact.com]