---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clustername
  namespace: fluentd
data:
  splunk_k8s_clustername: {{ .Values.clusterName | required "clusterName is required! Set with --set clusterName=<your-cluster-name>" }}
