apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: busybox-vault-test
  name: busybox-vault-test
  namespace: pbmp-dev
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: busybox-vault-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: ssis-database/creds/test-short-ttl
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "ssis-database/creds/test-short-ttl" -}}
            export SPRING_DATASOURCE_USERNAME="{{ .Data.username }}"
            export SPRING_DATASOURCE_PASSWORD="{{ .Data.password }}"
          {{- end }}
        vault.hashicorp.com/agent-pre-populate: "true"
        vault.hashicorp.com/role: test-short-ttl
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: busybox-vault-test
    spec:
      containers:
      - args:
        - -c
        - source /vault/secrets/config && sleep 8640
        command:
        - sh
        image: drydock.medimpact.com/busybox
        imagePullPolicy: IfNotPresent
        name: busybox-vault-test
        resources:
          limits:
            cpu: "1"
            memory: 400Mi
          requests:
            cpu: 125m
            memory: 395Mi
      securityContext:
        runAsUser: 70501
      serviceAccountName: pbmp-default
