apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pas-nonprod
  namespace: argocd
spec:
  description: API Management
  destinations:
  - name: aks-dev-westus2-001
    namespace: pas-dev
    server: 'https://aks-aks-dev-westus2-001-4aae88d7.hcp.westus2.azmk8s.io:443'
  - name: aks-dev-westus2-001
    namespace: pas-qa
    server: 'https://aks-aks-dev-westus2-001-4aae88d7.hcp.westus2.azmk8s.io:443'
  roles:
  - name: admin
    groups:
    - Kube_cluster-power-users
    policies:
    - p, proj:pas-nonprod:admin, applications, *, pas-nonprod/*, allow
  - name: developer
    groups:
    - Kube_dev_pas-dev
    - Kube_dev_pas-qa
    policies:
    - p, proj:pas-nonprod:developer, applications, get, pas-nonprod/*, allow
    - p, proj:pas-nonprod:developer, applications, sync, pas-nonprod/*, allow
  sourceRepos:
  - https://bitbucket.medimpact.com/scm/pas/pas-doc-ws.git
  - https://bitbucket.medimpact.com/scm/pas/pas-guideline-svc.git
  - https://bitbucket.medimpact.com/scm/pas/pas-harvest-svc.git
  - https://bitbucket.medimpact.com/scm/pas/pas-integration-ws.git
  - https://bitbucket.medimpact.com/scm/pas/pas-main-ui.git
  - https://bitbucket.medimpact.com/scm/pas/pas-odm-extractor.git
  - https://bitbucket.medimpact.com/scm/pas/pas-process-ws.git
  - https://bitbucket.medimpact.com/scm/pas/pas-rules-common.git
  - https://bitbucket.medimpact.com/scm/pas/pas-rules-pub-ws.git
  - https://bitbucket.medimpact.com/scm/pas/pas-rules-ws.git
  - https://bitbucket.medimpact.com/scm/pas/pas-scheduler.git
  - https://bitbucket.medimpact.com/scm/pas/pas-shared-cfg.git
  - https://bitbucket.medimpact.com/scm/pas/pas-ui.git
