---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opencve-redis
  name: opencve-redis
spec:
  type: ClusterIP
  ports:
  - name: opencve-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: opencve-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opencve-redis
  name: opencve-redis
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: opencve-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opencve-redis
    spec:
      containers:
      - name: redis
        image: docker-local.artifactory.medimpact.com/dockerhub/redis:7.0.12-alpine
        imagePullPolicy: IfNotPresent
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 6379 --no-auth-warning ping) == "PONG" ]; then exit 0; else exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 6379 --no-auth-warning ping) == "PONG" ]; then exit 0; else exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/redis/
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: opencve-redis
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault