---
apiVersion: v1
kind: Namespace
metadata:
  name: itsystems-prod
  labels:
    namespace: itsystems-prod
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pss-enforce: "true"
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: itsystems-prod
spec:
  hard:
    limits.cpu: 48000m
    limits.memory: 46G
    requests.cpu: 5000m
    requests.memory: 20G
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: itsystems-prod
spec:
  limits:
  - default:
      cpu: 150m
      memory: 125M
      ephemeral-storage: 5Gi
    defaultRequest:
      cpu: 50m
      memory: 100M
      ephemeral-storage: 100Mi
    max:
      ephemeral-storage: 10Gi
    type: Container
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: itsystems-prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress