# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.con-solns-prod.acc-portal-prod
  labels: 
    volname: con-solns-prod.acc-portal-prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.15.130.120
    path: "/vol_pv2medvfiler4_acc_portal_prod/qtree_acc_portal_prod"
