# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-prod-nfs
  namespace: ai-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: ai-prod.ai-prod-nfs
