# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inform-uat-filedrop
  namespace: mfs-uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 28G
  selector:
    matchLabels:
      volname: mfs-uat.inform-uat-filedrop
