# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usr2-newmed-out
  namespace: fmp-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: fmp-prod.prodazsqr1-out