# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rad-prod
  namespace: medadjust-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: medadjust-prod.rad-prod