# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itapps-confluence-prod
  namespace: itapps-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: nfs
  selector:
    matchLabels:
      volname: itapps-prod.itapps-confluence-prod
