# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.defectdojo-dev.defectdojo-dev
  labels: 
    volname: defectdojo-dev.defectdojo-dev
spec:
  capacity:
    storage: 160Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nfs
  nfs:
    server: 10.13.130.94
    path: "/vol_pv1medvfiler4_defectdojo_dev/defectdojo_dev"
