# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.ai-qa.pylibs-nonprod
  # annotations:
    # volume.beta.kubernetes.io/mount-options: rsize=8192,wsize=8192,timeo=14,intr,vers=3
  labels: 
    volname: ai-qa.pylibs-nonprod
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: nfs
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_ai_pylibs_nonprod/qtree_pv1medvfiler4_ai_pylibs_nonprod"