# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.sas-dev.sasviya-appdata-dev
  # annotations:
    # volume.beta.kubernetes.io/mount-options: rsize=8192,wsize=8192,timeo=14,intr,vers=3
  labels: 
    volname: sas-dev.sasviya-appdata-dev
spec:
  capacity:
    storage: 282Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: nfs
  nfs:
    server: 10.13.155.246
    path: "10.13.155.246:/pv1medvfiler3_sasviya_appdata_dev/qtree_sasviya_appdata"
