# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.mms-qa.inform-qa-filedrop
  labels: 
    volname: mms-qa.inform-qa-filedrop
spec:
  capacity:
    storage: 28G
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_qa_inform_ilm/qtree_inform_qa_filedrop"
