# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.corpcomm-dev.corp-sites-dev
  labels: 
    volname: corpcomm-dev.corp-sites-dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_corp_sites_dev/qtree_corp_sites_dev"
