# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-dev-nfs
  namespace: ai-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: ai-dev.ai-dev-nfs
