# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mmsp-dev
  namespace: mms-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  selector:
    matchLabels:
      volname: mms-dev.mmsp-dev
