# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-qa-nfs
  namespace: ai-qa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: ai-qa.ai-qa-nfs
