# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inform-dev-filedrop
  namespace: mfs-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 63G
  selector:
    matchLabels:
      volname: mfs-dev.inform-dev-filedrop
