# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-tools
  namespace: jenkins-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  
  selector:
    matchLabels:
      volname: jenkins-dev.jenkins-tools