# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sasviya-appdata-dev
  namespace: sas-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 282Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: sas-dev.sasviya-appdata-dev
