# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata-pmedgn-data
  namespace: pdp-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: pdp-dev.appdata-pmedgn-data
