# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-shares-dev-dest-data-entanalytics
  namespace: sas-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: sas-dev.sas-shares-dev-dest-data-entanalytics
