apiVersion: v1
kind: Secret
metadata:
  name: star-fullchain.medimpact.com.tls
  namespace: ingress-nginx
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIG7TCCBdWgAwIBAgIQBxMhahkCEea5I3ahAn6l1DANBgkqhkiG9w0BAQsFADBZ
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
    aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjQx
    MDIzMDAwMDAwWhcNMjUxMDIzMjM1OTU5WjB9MQswCQYDVQQGEwJVUzETMBEGA1UE
    CBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJU2FuIERpZWdvMSswKQYDVQQKEyJNZWRJ
    bXBhY3QgSGVhbHRoY2FyZSBTeXN0ZW1zLCBJbmMuMRgwFgYDVQQDDA8qLm1lZGlt
    cGFjdC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYQ3JVfi2j
    +yvMOPORaeDpRwdis1869oEQE5rx/eM7NpZUVrMC0NUN7AitVZnOy/7uubPs35OS
    xdCNRryYD2qKuYPFxMaaNLAWDEIM0bVjgZDHOvXCmearSsPfLf2UZ/GJQAr2ggzH
    AnpkqHV1kz5jc+ZrTDT+gX4ot/+V0W7rb6lA7PXMgbCpwYZJ7YYXcaXLx0Rmwt+D
    JjZ7QVq0NW358gQwMo/ONXGw8PzzSHyd1c9hPHHzGjpPQVd3rg3Xkxt2iWYl9NCc
    ybRtg/S96b6JlTz1skdVhoLiB/BySKGCy93W9oV2WyMSukcUqMgQRsPtcH9sN9kB
    jYMfb/tvnXaPAgMBAAGjggOLMIIDhzAfBgNVHSMEGDAWgBR0hYDAZsffN97PvSk3
    qgMdvu3NFzAdBgNVHQ4EFgQUVvGvV5idjHfbB6zrLIIO6ga8QZ4wGgYDVR0RBBMw
    EYIPKi5tZWRpbXBhY3QuY29tMD4GA1UdIAQ3MDUwMwYGZ4EMAQICMCkwJwYIKwYB
    BQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMC
    BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGfBgNVHR8EgZcwgZQw
    SKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbEcy
    VExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDBIoEagRIZCaHR0cDovL2NybDQuZGln
    aWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIwQ0ExLTEu
    Y3JsMIGHBggrBgEFBQcBAQR7MHkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
    Z2ljZXJ0LmNvbTBRBggrBgEFBQcwAoZFaHR0cDovL2NhY2VydHMuZGlnaWNlcnQu
    Y29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIwQ0ExLTEuY3J0MAwG
    A1UdEwEB/wQCMAAwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2ABLxTjS9U3JM
    hAYZw48/ehP457Vih4icbTAFhOvlhiY6AAABkrdlpYMAAAQDAEcwRQIgaCqWisUq
    U5twXbwzeDULBPjA6GIYph6CHncPznANKjwCIQC1pkzEgIKKcQrw8SfhthaLXBqK
    AkhCCE1R5YY/YlI1CAB1AObSMWNAd4zBEEEG13G5zsHSQPaWhIb7uocyHf0eN45Q
    AAABkrdlpREAAAQDAEYwRAIgVv2qdtFDxhBcbgeCAGzu6B5doVXg9AHcIGvKVZHU
    ToICIGkxCmkL7y0d3qdZ4vsO9nAZ9kj9Y71rFaBWfNdNPv9bAHcAzPsPaoVxCWX+
    lZtTzumyfCLphVwNl422qX5UwP5MDbAAAAGSt2WlHAAABAMASDBGAiEA5v43i/W1
    k13ejrYNu51PtUtaU9Tyd6Gm8uEPjbEiIAgCIQDgvwnt13lOectOWfKc23r68X/R
    UxWDX1D63SpJh7K0STANBgkqhkiG9w0BAQsFAAOCAQEAO4fYFpnO+pa6Pw8dmR77
    mjHgTskw8oPSY8iJVvXuHr2Q+8Z1VYjpuZ30pfp6iVZ7pnIY6tkYSXpPs+zgEMph
    AjyQsO39kIFrYe2upvBIUKFJ9FoEt4YlOf+QXZegif5ma5HWcWSv9Dkkvulw6ZpD
    oaCdieE1Y4BsIrQMqsch5ZFCZUv6XLm6WSidGOZaDt/k9g7A6wMagK1L9SYXgwTF
    rmnw52QJrD4ErIqf0fhuPew0DjMLclNrm/D+56RAOPwr9SiE+Si2oha6R1GGn0gT
    /LnAQpvQ3z2Sy7bM1+F0ErVXzpWhF7VcQG2p24mNDpjnAv00mZlq1EO+Y/kkqx0/
    pQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEyDCCA7CgAwIBAgIQDPW9BitWAvR6uFAsI8zwZjANBgkqhkiG9w0BAQsFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
    MjAeFw0yMTAzMzAwMDAwMDBaFw0zMTAzMjkyMzU5NTlaMFkxCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxMzAxBgNVBAMTKkRpZ2lDZXJ0IEdsb2Jh
    bCBHMiBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAMz3EGJPprtjb+2QUlbFbSd7ehJWivH0+dbn4Y+9lavyYEEV
    cNsSAPonCrVXOFt9slGTcZUOakGUWzUb+nv6u8W+JDD+Vu/E832X4xT1FE3LpxDy
    FuqrIvAxIhFhaZAmunjZlx/jfWardUSVc8is/+9dCopZQ+GssjoP80j812s3wWPc
    3kbW20X+fSP9kOhRBx5Ro1/tSUZUfyyIxfQTnJcVPAPooTncaQwywa8WV0yUR0J8
    osicfebUTVSvQpmowQTCd5zWSOTOEeAqgJnwQ3DPP3Zr0UxJqyRewg2C/Uaoq2yT
    zGJSQnWS+Jr6Xl6ysGHlHx+5fwmY6D36g39HaaECAwEAAaOCAYIwggF+MBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFHSFgMBmx9833s+9KTeqAx2+7c0XMB8G
    A1UdIwQYMBaAFE4iVCAYlebjbuYP+vq5Eu0GF485MA4GA1UdDwEB/wQEAwIBhjAd
    BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdgYIKwYBBQUHAQEEajBoMCQG
    CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQAYIKwYBBQUHMAKG
    NGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RH
    Mi5jcnQwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
    L0RpZ2lDZXJ0R2xvYmFsUm9vdEcyLmNybDA9BgNVHSAENjA0MAsGCWCGSAGG/WwC
    ATAHBgVngQwBATAIBgZngQwBAgEwCAYGZ4EMAQICMAgGBmeBDAECAzANBgkqhkiG
    9w0BAQsFAAOCAQEAkPFwyyiXaZd8dP3A+iZ7U6utzWX9upwGnIrXWkOH7U1MVl+t
    wcW1BSAuWdH/SvWgKtiwla3JLko716f2b4gp/DA/JIS7w7d7kwcsr4drdjPtAFVS
    slme5LnQ89/nD/7d+MS5EHKBCQRfz5eeLjJ1js+aWNJXMX43AYGyZm0pGrFmCW3R
    bpD0ufovARTFXFZkAdl9h6g4U5+LXUZtXMYnhIHUfoyMo5tS58aI7Dd8KvvwVVo4
    chDYABPPTHPbqjc1qCmBaZx2vN4Ye5DUys/vZwP9BFohFrH/6j/f3IL16/RZkiMN
    JCqVJUzKoZHm1Lesh3Sz8W2jmdv51b2EQJ8HmA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
    MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
    b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
    2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
    1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
    q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
    tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
    vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
    BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
    5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
    1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
    NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
    Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
    8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
    pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
    MrY=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYQ3JVfi2j+yvM
    OPORaeDpRwdis1869oEQE5rx/eM7NpZUVrMC0NUN7AitVZnOy/7uubPs35OSxdCN
    RryYD2qKuYPFxMaaNLAWDEIM0bVjgZDHOvXCmearSsPfLf2UZ/GJQAr2ggzHAnpk
    qHV1kz5jc+ZrTDT+gX4ot/+V0W7rb6lA7PXMgbCpwYZJ7YYXcaXLx0Rmwt+DJjZ7
    QVq0NW358gQwMo/ONXGw8PzzSHyd1c9hPHHzGjpPQVd3rg3Xkxt2iWYl9NCcybRt
    g/S96b6JlTz1skdVhoLiB/BySKGCy93W9oV2WyMSukcUqMgQRsPtcH9sN9kBjYMf
    b/tvnXaPAgMBAAECggEBAJ2lBMo3UVPQuwuClGJyuOWzxjl3obqciFZMxE0UkrjO
    QOU30gQCcNxWK7kWxijN4YbpzbOlArEiC7WAU+fQjQyU0O6wU0mDkLxxsRAhKkVf
    5EamvxFdGJ3SwVeF8exlnNc83QD2qhPDxa5scjsD252pldSvV44SnQFXpzLx2RY7
    FxLnFLDhVSwIlFH4oGftNtD2iYCMoU8By8FEPSGjHzse/5dhQ1kDP4JPCrJ5PcMe
    W4YtCXPwaCH3zb9oBchmMNgQFBeg/MBJRMesljVi5nxT4iRjagcsqPG5ibs8b0W2
    usaxXwSkgdwvKnqnWD5lPn1gR4gBaph5xc+enEJtj5ECgYEA8UwKLIMRIuoP6Cs2
    fEpC6Za9Ou1svqHzuRXlgJ7Dflx9U1R9JZDVFEmlicuTA0puenzSJnpP8lO7khtQ
    2A+QBONHHi6sgjBkkAWyfCVNdowQyOoATFBgn962b97RHArTtq/vLufeoa51oj+L
    w6z2qqHSmUnJK278J8a44n+1wUcCgYEA5XDpXnDBkjzHAJJs1w1Hmy5DkhOtIfVu
    V5cTnWRfI3K+9rDCeF59ZpXU9XF0jsOQwC+nQy/86jhCE4mSNNSfBNurzaZ//zyf
    VOr9xZm2uhoheH9OQNyndtn1IIBmWtQv0PS1vN1FqtvXa3gEnUGarRWWJTyauR2e
    O3Ba/j7QBHkCgYA7qwABDdAZACQ61yS8C2kMdjgI8FkpssagCCgebCQPhTOAfa4M
    sgne4G9M6chK0gcLxv34gdpvJAGIGbUeGIsWilU1w3jpIKpdaus+A8NqAyzLYgH8
    3QtnvR0EAOdYtdywmkTdJn1JIej43Bnlo0nD3AxF15clZGZ6N4vUhpwdVQKBgFaJ
    RZuXD4smXTA8Ccz6dz1yL44S2cPrG5jxpDZCuxdVmezVMiPQD5/3dwCzr/CAlkHG
    N2HB4bQ9T76qrng6kVd1utCvsasEpFuU3e3/UcnTPTiDW3JfRtIu1qNRiklLqlU3
    VqxLEJGmpRMliyf8rGgHsj+NIhYbs6hbchZefnqRAoGBAKQR7yNPet3cOZJlEADg
    7OhpatItUMVKKvdu4y+vP3h/Fbu33SxZ6KQBnv0sHNpc91b8WosA2SiuKsDFtocY
    mdFufAdp4nggQbof5IAuM6PicVF3vNzeyYzBWK0v714ibVPfcUYZ4CHHVtgFK3hc
    jgyn9xAD9EpRII1GEmXHhr6n
    -----END PRIVATE KEY-----
