{
 "title": "Calico",
 "tags": [ "calico" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99,sum(irate(process_cpu_seconds_total{job=\"calico-node\",cluster=~\"$cluster\"}[5m]))by(pod))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg (container_memory_working_set_bytes{pod=~\"calico-node-.*\", namespace=\"kube-system\",cluster=~\"$cluster\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(felix_host{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_endpoints{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exec Time p99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(felix_exec_time_micros{quantile=\"0.99\",cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Update Apply Duration p99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_apply_time_seconds{quantile=\"0.99\",cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Update Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_failures{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_messages{cluster=~\"$cluster\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Message Batch Sizes p99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_msg_batch_size{quantile=\"0.99\",cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "iptables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active Chains",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(felix_iptables_chains{cluster=~\"$cluster\"}) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Active Rules",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(felix_iptables_rules{cluster=~\"$cluster\"}) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Lines Executed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (increase(felix_iptables_lines_executed{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "IPTables Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_calls{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Save"
    },
    {
     "expr": "sum(rate(felix_iptables_restore_calls{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Restore"
    }
   ]
  },
  {
   "title": "Save Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_iptables_save_errors{cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Restore Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_iptables_restore_errors{cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}