{
 "title": "Namespace Usage Quota",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Request > 50%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(kube_resourcequota{resource=\"requests.cpu\", type=\"used\",cluster=~\"$cluster\"}) by (namespace, cluster) / sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\",cluster=~\"$cluster\"} > 1) by (namespace, cluster) > 0.5)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Limit > 50%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\",cluster=~\"$cluster\"}) by (namespace, cluster) / sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\",cluster=~\"$cluster\"} > 2) by (namespace, cluster) > 0.5)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Request > 50%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(kube_resourcequota{resource=\"requests.memory\", type=\"used\",cluster=~\"$cluster\"}) by (namespace, cluster) / sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\",cluster=~\"$cluster\"} > 2) by (namespace, cluster) > 0.5)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Limit > 50%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\",cluster=~\"$cluster\"}) by (namespace, cluster) / sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\",cluster=~\"$cluster\"} > 2) by (namespace, cluster) > 0.5)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Headless Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
     "options": {
      "content": "\nWarning: The below panels are for headless alert configurations. Graphical representation only reflects the reality of the current cluster.\n\n\n"
     }
    },
    {
     "title": "CPU Request > 50%",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(kube_resourcequota{resource=\"requests.cpu\", type=\"used\"}) by (namespace) / sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\"} > 1) by (namespace) > 0.5)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "CPU Limit > 50%",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\"}) by (namespace) / sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\"} > 2) by (namespace) > 0.5)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory Request > 50%",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(kube_resourcequota{resource=\"requests.memory\", type=\"used\"}) by (namespace) / sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\"} > 2) by (namespace) > 0.5)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory Limit > 50%",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\"}) by (namespace) / sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\"} > 2) by (namespace) > 0.5)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}