{
 "title": "HSSID Default Dashboard",
 "tags": [ "HSSID" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"^(pbmp.*|dmp-.*|fmp-.*|pap-.*)\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"used\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) / sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\",namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) / sum(kube_resourcequota{resource=\"limits.cpu\", type=\"hard\",namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase!=\"\",namespace=~\"$namespace\",cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Istio Proxy Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container=\"istio-proxy\", namespace=~\"$namespace\",cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top CPU Containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[2m])) by (pod, container, cluster))",
     "legendFormat": "{{ container }} in {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"used\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) / sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\",namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) / sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\",namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_service_spec_type{namespace=~\"$namespace\", type!=\"\",cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_ingress_info{namespace=~\"$namespace\", ingress!=\"\",cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Most Throttled Containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, (sum(increase(container_cpu_cfs_throttled_periods_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[2m])) by (pod, container)) /sum(increase(container_cpu_cfs_periods_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[2m])) by (pod, container))",
     "legendFormat": "{{ container }} in {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Restarting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[$__range]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 2, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace)(delta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[1m]) > 0)",
     "legendFormat": "{{pod}} in {{namespace}}"
    }
   ]
  },
  {
   "title": "Most restarts",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "topk(1, kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Top Memory Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase!=\"Running\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*no[0-9]+\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Newest Pods",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "bottomk(30, sort(time() - kube_pod_status_scheduled_time{namespace=~\"$namespace\",cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Top Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\",pod!=\"\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[4m]))))",
     "legendFormat": "RX: {{ pod }}"
    },
    {
     "expr": "topk(5, sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\",pod!=\"\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[4m]))))",
     "legendFormat": "TX: {{ pod }}"
    }
   ]
  }
 ]
}