apiVersion: v1
kind: Service
metadata:
  name: ROUTER-headless
  namespace: ppas-dev
spec:
  clusterIP: None
  ports:
  - name: tcp-zmq
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: ROUTER
  sessionAffinity: None
  type: ClusterIP