kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pfwa-prod
  # annotations:
    # storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "k8s pfwa-prod persistent volumes"  #Optional Parameter
# datastoreurl: "ds:///vmfs/volumes/vsan:52cdfa80721ff516-ea1e993113acfc77/" #Optional Parameter
# csi.storage.k8s.io/fstype: "ext4" #Optional Parameter
allowedTopologies:
  - matchLabelExpressions:
      # - key: topology.csi.vmware.com/k8s-region
      # - key: failure-domain.beta.kubernetes.io/region   
      - key: topology.kubernetes.io/region   
        values:
          - ca
      # - key: topology.csi.vmware.com/k8s-zone
      # - key: failure-domain.beta.kubernetes.io/zone
      - key: topology.kubernetes.io/zone
        values:
          - zone-a
          - zone-b
