---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-local-cache-redis
  name: docker-local-cache-redis
spec:
  type: ClusterIP
  ports:
  - name: docker-local-cache-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: docker-local-cache-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-local-cache-redis
  name: docker-local-cache-redis
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: docker-local-cache-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker-local-cache-redis
    spec:
      containers:
      - name: redis
        image: docker-local.artifactory.medimpact.com/dockerhub/redis:7.0.12-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASSWORD
          value: "peithei8caish6uW3ooz"
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 6379 --no-auth-warning -a "${REDIS_PASSWORD}" ping) == "PONG" ]; then exit 0; else exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 6379 --no-auth-warning -a "${REDIS_PASSWORD}" ping) == "PONG" ]; then exit 0; else exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/redis/
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: docker-local-cache-redis-config
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault