apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: iam-dev-iam-okta-ldap-connector
  name: okta-ldap-connector-configmap2
  namespace: iam-lab
data:
  ADDITIONAL-LOCATION: /etc/config/
  PROFILE-DEV: dev
