# apiVersion: v1
# kind: ConfigMap
# metadata:
  # labels:
    # app.kubernetes.io/instance: iam-dev-iam-okta-ldap-connector
  # name: okta-ldap-connector-configmap
  # namespace: iam-dev
# data:
  # application-dev.yaml: "spring:\n  application:\n    name: okta-ldap-connector\nserver:
    # \n  forward-headers-strategy: framework\n  port: 8080\nswagger:\n   prefixpath:\n\n\nldap:\n
    # \ host: deviamldaprw.medimpact.com\n  port: 389\n  ssl: false\n  baseDn: dc=medimpact,dc=com\n
    # \ uniqueIdentifier: nsUniqueId\n  credentials:\n    #        adminUser: \n    #
    # \       adminPassword: \n  userSettings:\n    objectClass: customPerson\n    objectClasses:\n
    # \     - customPerson\n      - person\n      - organizationalPerson\n      - inetOrgPerson\n
    # \     - top\n    prefix: uid\n    container: ou=people\n\n    containers:\n      internal:
    # ou=internal\n      external: ou=external\n\n  groupSettings:\n    objectClass:
    # groupOfUniqueNames\n    objectClasses:\n      - groupOfUniqueNames\n      - top\n
    # \   prefix: cn\n    container: ou=group\n    memberAttribute: uniqueMember\n\nokta:\n
    # \ appName: myrxpbm-dev_ldapscimconnector_1\n  mapping:\n    userAccountType: userAccountType\n
    # \   title: title\n    homePhone: homePhone\n    state: state\n    employeeNumber:
    # employeeNumber\n    employeeType: employeeType\n    profession: profession\n    organization:
    # organization\n    contactType: contactType\n    manufacturer: manufacturer\n    labeler:
    # labeler\n    applicationName: applicationName\n    userType: userType\n    physProviderId:
    # physProviderId\n    groups: groups  \n"
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: iam-dev-iam-okta-ldap-connector
  name: okta-ldap-connector-configmap
  namespace: iam-lab
data:
  application-dev.yaml: |
    spring:
      application:
        name: okta-ldap-connector
    server:
      forward-headers-strategy: framework
      port: 8080
    swagger:
      prefixpath:

    ldap:
      host: deviamldaprw.medimpact.com
      port: 389
      ssl: false
      baseDn: dc=medimpact,dc=com
      uniqueIdentifier: nsUniqueId
      credentials:
        # adminUser:
        # adminPassword:
      userSettings:
        objectClass: customPerson
        objectClasses:
          - customPerson
          - person
          - organizationalPerson
          - inetOrgPerson
          - top
        prefix: uid
        container: ou=people
        containers:
          internal: ou=internal
          external: ou=external
      
      groupSettings:
        objectClass: groupOfUniqueNames
        objectClasses:
          - groupOfUniqueNames
          - top
        prefix: cn
        container: ou=group
        memberAttribute: uniqueMember
    
    okta:
      appName: myrxpbm-dev_ldapscimconnector_1
      mapping:
        userAccountType: userAccountType
        title: title
        homePhone: homePhone
        state: state
        employeeNumber: employeeNumber
        employeeType: employeeType
        profession: profession
        organization: organization
        contactType: contactType
        manufacturer: manufacturer
        labeler: labeler
        applicationName: applicationName
        userType: userType
        physProviderId: physProviderId
        groups: groups
