apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: okta-ldap-connector
    app.kubernetes.io/instance: iam-dev-iam-okta-ldap-connector
    version: 0.1.46
  name: okta-ldap-connector
  namespace: iam-lab
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: okta-ldap-connector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config-1: iams-kv/data/okta-ldap-connector-dev
        vault.hashicorp.com/agent-inject-template-config-1: |
          {{ with secret "iams-kv/data/okta-ldap-connector-dev" -}}
            export LDAP_CREDENTIALS_ADMINUSER="{{ .Data.data.ADMINUSER }}"
            export LDAP_CREDENTIALS_ADMINPASSWORD="{{ .Data.data.ADMINPASSWORD }}"
          {{- end }}
        vault.hashicorp.com/agent-pre-populate: "true"
        vault.hashicorp.com/role: iams-okta-ldap-connector
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: okta-ldap-connector
    spec:
      containers:
      - args:
        - -c
        - source /vault/secrets/config-1 && java -Duser.timezone=PST $JVM_OPTS -jar
          app.jar
        command:
        - /bin/sh
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: PROFILE-DEV
              name: okta-ldap-connector-configmap2
        - name: SPRING_CONFIG_ADDITIONAL-LOCATION
          valueFrom:
            configMapKeyRef:
              key: ADDITIONAL-LOCATION
              name: okta-ldap-connector-configmap2
        - name: JVM_OPTS
          value: -Xms64m -Xmx400m -Duser.timezone=PST
        image: docker-local.artifactory.medimpact.com/com/medimpact/iam/okta-ldap-connector:0.1.46
        imagePullPolicy: Always
        name: okta-ldap-connector
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 250Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      securityContext:
        runAsUser: 777
      serviceAccountName: iam-default
      volumes:
      - configMap:
          defaultMode: 420
          name: okta-ldap-connector-configmap
        name: config-volume
