apiVersion: v1
kind: Namespace
metadata:
  name: vmware-system-csi
  labels:
    istio-injection: disabled
    namespace: vmware-system-csi
---
# Default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: vmware-system-csi
spec:
  podSelector: {}
---
# Allow all traffic within the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-within-namespace
  namespace: vmware-system-csi
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}