---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lb.medimpact.com/haproxyServerOptions: check
    lb.medimpact.com/loadBalancerIPs: 10.13.158.134
    lb.medimpact.com/loadBalancerIdentifier: eda1371f-f1a5-40dc-aed9-b7e69653a6e6
    lb.medimpact.com/loadBalancerType: haproxy
  name: rabbitmq-itsys-001-0-nodeport
  namespace: itsystems-lab
spec:
  type: LoadBalancer
  ports:
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     # nodePort: 30672
   # - name: http-mgmt
     # protocol: TCP
     # port: 15672
     # targetPort: 15672
     # # nodePort: 31672
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-itsys-001-0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lb.medimpact.com/haproxyServerOptions: check
    lb.medimpact.com/loadBalancerIPs: 10.13.158.134
    lb.medimpact.com/loadBalancerIdentifier: eda1371f-f1a5-40dc-aed9-b7e69653a6e6
    lb.medimpact.com/loadBalancerType: haproxy
  name: rabbitmq-itsys-001-1-nodeport
  namespace: itsystems-lab
spec:
  type: LoadBalancer
  ports:
   - name: amqp
     protocol: TCP
     port: 5673
     targetPort: 5672
     # nodePort: 30673
   # - name: http-mgmt
     # protocol: TCP
     # port: 15672
     # targetPort: 15672
     # # nodePort: 31673
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-itsys-001-1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lb.medimpact.com/haproxyServerOptions: check
    lb.medimpact.com/loadBalancerIPs: 10.13.158.134
    lb.medimpact.com/loadBalancerIdentifier: eda1371f-f1a5-40dc-aed9-b7e69653a6e6
    lb.medimpact.com/loadBalancerType: haproxy
  name: rabbitmq-itsys-001-2-nodeport
  namespace: itsystems-lab
spec:
  type: LoadBalancer
  ports:
   - name: amqp
     protocol: TCP
     port: 5674
     targetPort: 5672
     # nodePort: 30674
   # - name: http-mgmt
     # protocol: TCP
     # port: 15672
     # targetPort: 15672
     # # nodePort: 31674
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-itsys-001-2