---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  - pods
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
  namespace: fluentd
subjects:
- kind: ServiceAccount
  name: fluentd # Name is case sensitive
  namespace: fluentd
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: fluentd # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
