# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.mfs-uat.inform-uat-filedrop
  labels: 
    volname: mfs-uat.inform-uat-filedrop
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_mfs_uat_filedrop/qtree_filedrop"
