# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.clm-uat.clmstore-uat
  labels: 
    volname: clm-uat.clmstore-uat
spec:
  capacity:
    storage: 499Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_clmstore_uat/clmstore_uat"
