# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdrp-appdata-e2e-data-mdrp
  namespace: mfs-e2e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mfs-e2e.mdrp-appdata-e2e-data-mdrp
