apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  additional-scrape-configs.yaml: |
    - job_name: etcd
      scheme: https
      scrape_interval: 10s
      static_configs:
      - targets: ['dv1medk8ma01.medimpact.com:2379', 'dv1medk8ma02.medimpact.com:2379', 'dv1medk8ma03.medimpact.com:2379', 'dv2medk8ma04.medimpact.com:2379', 'dv2medk8ma05.medimpact.com:2379']
      tls_config:
        ca_file: /etc/prometheus/secrets/etcd-certs/ca.crt
        cert_file: /etc/prometheus/secrets/etcd-certs/clientpeer.crt
        key_file: /etc/prometheus/secrets/etcd-certs/clientpeer.key
    - job_name: 'vault'
      scrape_interval: 20s
      metrics_path: "/v1/sys/metrics"
      # vault_route_(method)_(engine)_
      # vault_route_(method)_(engine)__count
      # vault_route_(method)_(engine)__sum
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(vault_route)_([[:alnum:]]+)_(.*[[:alnum:]]+)_(.*)'
        replacement: '${2}'
        target_label: method
      - source_labels: [__name__]
        regex: '(vault_route)_([[:alnum:]]+)_(.*[[:alnum:]]+)_(.*)'
        replacement: '${3}'
        target_label: engine
      - source_labels: [__name__]
        regex: '(vault_route)_([[:alnum:]]+)_(.*[[:alnum:]]+)_(.*)'
        replacement: '${1}_method_${4}'
        target_label: __name__
      params:
        format: ['prometheus']
      scheme: https
      tls_config:
        # ca_file: your_ca_here.pem
        insecure_skip_verify: true
      bearer_token: "your_vault_token_here"
      static_configs:
      - targets: ['vault-az.medimpact.com:8200','vault-ca.medimpact.com:8200','vault-dev.medimpact.com:8200']
    # - job_name: jenkins
      # scheme: https
      # scrape_interval: 10s
      # static_configs:
      # - targets: ['jenkins.medimpact.com']
      # metrics_path: "/prometheus"
    # - job_name: mongo
      # scheme: http
      # scrape_interval: 10s
      # static_configs:
      # - targets: ['dv1medm0n1.medimpact.com:9216', 'dv1medm0n2.medimpact.com:9216', 'dv1medm0n3.medimpact.com:9216']