---
apiVersion: v1
kind: Namespace
metadata:
  name: bia-prod
  labels:
    istio-injection: disabled
    namespace: bia-prod
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pss-enforce: "true"
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: bia-prod
spec:
  hard:
    limits.cpu: 302000m
    limits.memory: 190G
    requests.cpu: 20000m
    requests.memory: 94G
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: bia-prod
spec:
  limits:
  - default:
      cpu: 150m
      memory: 125M
      ephemeral-storage: 5Gi
    defaultRequest:
      cpu: 10m
      memory: 100M
      ephemeral-storage: 100Mi
    max:
      ephemeral-storage: 10Gi
    type: Container
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: bia-prod
spec:
  podSelector: {}
---
#bind AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_prod_bia-prod
  namespace: bia-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kube_prod_bia-prod
---
#bind AD group to the viewers role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_prod_bia-prod-ro
  namespace: bia-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-viewers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kube_prod_bia-prod-ro
---
#bind power-users AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_cluster-power-users
  namespace: bia-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kube_cluster-power-users
