apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-medresponse-prod-pv2medvfiler3-pafa-prod
  # annotations:
    # volume.beta.kubernetes.io/mount-options: rsize=8192,wsize=8192,timeo=14,intr,vers=3
  labels: 
    volname: medresponse-prod-pv2medvfiler3-pafa-prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.15.130.188
    path: "/pv2medvfiler3_vol_pafa_prod/qtree_pafa_prod"