apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: itsystems-lab
spec:
  serviceName: sentinel
  replicas: 3
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      initContainers:
      - name: config
        image: docker-local.artifactory.medimpact.com/dockerhub/redis:6.2.7-alpine
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c" ]
        args:
          - |
            REDIS_PASSWORD=dok2maiNahX%
            HOSTNAME="$(hostname)"
            INDEX="${HOSTNAME##*-}"
            eval MY_SENTINEL_ID="\${SENTINEL_ID_$INDEX}"
            MASTER_FQDN=$(hostname -f | sed -e 's/sentinel-[0-9]\.sentinel\./redis-0.redis./')
            SLAVE_1_FQDN=$(hostname -f | sed -e 's/sentinel-[0-9]\.sentinel\./redis-1.redis./')
            SLAVE_2_FQDN=$(hostname -f | sed -e 's/sentinel-[0-9]\.sentinel\./redis-2.redis./')
            SENTINEL_0_FQDN=$(hostname -f | sed -e 's/sentinel-[0-9]\./sentinel-0./')
            SENTINEL_1_FQDN=$(hostname -f | sed -e 's/sentinel-[0-9]\./sentinel-1./')
            SENTINEL_2_FQDN=$(hostname -f | sed -e 's/sentinel-[0-9]\./sentinel-2./')
            POD_FQDN=$(hostname -f)
            echo "port 26379
            protected-mode no
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            sentinel announce-ip $POD_FQDN
            sentinel announce-port 26379
            sentinel monitor mymaster $MASTER_FQDN 6379 2
            sentinel down-after-milliseconds mymaster 3000
            sentinel failover-timeout mymaster 6000
            sentinel parallel-syncs mymaster 1
            sentinel auth-pass mymaster $REDIS_PASSWORD
            
            # Generated by CONFIG REWRITE
            user default on nopass ~* &* +@all
            dir "/data"
            sentinel myid $MY_SENTINEL_ID
            sentinel known-sentinel mymaster $SENTINEL_0_FQDN 26379 $SENTINEL_ID_0
            sentinel known-sentinel mymaster $SENTINEL_1_FQDN 26379 $SENTINEL_ID_1
            sentinel known-sentinel mymaster $SENTINEL_2_FQDN 26379 $SENTINEL_ID_2
            sentinel known-replica mymaster $SLAVE_1_FQDN 6379
            sentinel known-replica mymaster $SLAVE_2_FQDN 6379
            
            sentinel config-epoch mymaster 0
            sentinel leader-epoch mymaster 0
            sentinel current-epoch 0
            " > /etc/redis/sentinel.conf
            grep -v "sentinel known-sentinel mymaster $POD_FQDN" /etc/redis/sentinel.conf > /etc/redis/sentinel.tmp && mv /etc/redis/sentinel.tmp /etc/redis/sentinel.conf
            cat /etc/redis/sentinel.conf
        env:
        - name: SENTINEL_ID_0
          value: 1283b2a1777a57dcfb0edad810c7e8787ca57d98
        - name: SENTINEL_ID_1
          value: a85712599642686d845163893d81f1d1c649ca48
        - name: SENTINEL_ID_2
          value: 13884559b8c6d8c60d6bb4b27115c2dfbef5c59c
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      containers:
      - name: sentinel
        image: docker-local.artifactory.medimpact.com/dockerhub/redis:6.2.7-alpine
        imagePullPolicy: IfNotPresent
        command: ["redis-sentinel"]
        args: ["/etc/redis/sentinel.conf"]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 26379 ping) != "PONG" ]; then exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 26379 ping) != "PONG" ]; then exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 26379
          name: sentinel
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      volumes:
      - name: redis-config
        emptyDir: {}
      securityContext:
        runAsUser: 999
  updateStrategy:
    type: RollingUpdate