apiVersion: v1
kind: Secret
metadata:
  name: pmm-secret
  labels:
    app.kubernetes.io/name: pmm
type: Opaque
stringData:
  PMM_ADMIN_PASSWORD: tai6Ooyooyeidaes7Goi
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: 02a9204c-6923-4f00-9fda-a1e4af95f4da
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: m0EBoOjfygQtT8Ng-aBQBqDd550UaXL4G3UDep8O
  GFHOST: pmm-dev