# Default password "admin", use bcrypt ($2a$ version) to generate a new one
adminPasswordBcrypt: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
adminEmail: mark.deckert@medimpact.com
adminFirstName:
adminLastName:
jwtSecret: myJWT4Gr4v1t33_S3cr3t
alerts:
  enabled: false
  # endpoints:
    # - http://grav-ae-engine:82/
  # security:
    # enabled: true
    # username: admin
    # password: adminadmin
api:
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 3
  # http:
    # services:
      # core:
        # http:
          # ingress:
            # hosts:
            # - "grav-dev-api.medimpact.com"
            # tls:
              # hosts:
              # - "grav-dev-api.medimpact.com"
  env:
  - name: gravitee_jwt_cookie-domain
    value: "gio-lab.medimpact.com"
  image:
    repository: docker-local.artifactory.medimpact.com/graviteeio/apim-management-api
    pullPolicy: IfNotPresent
    tag: 3.5.8-mi1.0.13
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    management:
      hosts:
      - "gio-lab.medimpact.com"
      path: /management
      tls:
        - hosts:
          - "gio-lab.medimpact.com"
    portal:
      hosts:
      - "gio-lab.medimpact.com"
      path: /portal
      tls:
        - hosts:
          - "gio-lab.medimpact.com"
  lifecycle:
    preStop: '["/bin/sh","-c","sleep 10"]'
  logging:
    debug: true
    stdout:
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file:
      enabled: false
      rollingPolicy: |
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${gravitee.management.log.dir}/gravitee_%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
        </rollingPolicy>
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%n"
    graviteeLevel: INFO
    jettyLevel: INFO
  user:
    login:
      defaultApplication: false
  replicaCount: 3
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 150m
      memory: 512Mi
  
elasticsearch:
  # Create an es cluster inside k8s (no)
  enabled: false
es:
  enabled: true
  cluster: elasticsearch
  index: gravitee
  # If the details for security are entered
  # authentication will be provided for the
  # elastic search cluster
  # https://docs.gravitee.io/apim_installguide_repositories_elasticsearch.html#management_api_configuration
  security:
    enabled: false
    username: example
    password: example
  ssl:
    enabled: false
    # keystore:
    #   type: jks
    #   path: path/to/jks
    #   password: example
    #   certs:
    #     - /path/to/cert1
    #     - /path/to/cert2
    #   keys:
    #     - /path/to/key
    #     - /path/to/key2
  endpoints:
  - "http://dv1medgravpoc1.medimpact.com:9200"
gateway:
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 3
  env:
  - name: gravitee_reporters_file_enabled
    value: "false"
  - name: JAVA_OPTS
    value: "-Djavax.net.ssl.trustStore=/opt/graviteeio-gateway/certs/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
  - name: GIO_MIN_MEM
    value: "1024m"
  - name: GIO_MAX_MEM
    value: "1024m"
  apiKey:
    header: X-Api-Key
    param: api-key
  image:
    repository: docker-local.artifactory.medimpact.com/graviteeio/apim-gateway
    pullPolicy: IfNotPresent
    tag: 3.5.8-mi1.0.13
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - "api-lab.medimpact.com"
    path: /
    tls:
      - hosts:
        - "api-lab.medimpact.com"
  lifecycle:
    preStop: '["/bin/sh","-c","sleep 10"]'
  logging:
    debug: true
    stdout:
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] [%X{api}] %-5level %logger{36} - %msg%n"
    file:
      enabled: false
      rollingPolicy: |
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${gravitee.home}/logs/gravitee_%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 30 days' worth of history -->
            <maxHistory>30</maxHistory>
        </rollingPolicy>
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] [%X{api}] %-5level %logger{36} - %msg%n"
    graviteeLevel: INFO
    jettyLevel: WARN
  resources:
    limits:
      cpu: 2000m
      memory: 1536Mi
    requests:
      cpu: 150m
      memory: 512Mi
  replicaCount: 3
  # sharding_tags: k8calab
  # unknown-expire-after: 604800 #default 604800
  ssl:
    enabled: false
  #  keystore:
  #    type: jks # Supports jks, pem, pkcs12
  #    path: ${gravitee.home}/certs/server-keystore.jks
  #    password: LeiK8aitiaBae
    clientAuth: false # Supports false/none, request, true/requires
  #  truststore:
  #    type: jks # Supports jks, pem, pkcs12
  #    path: ${gravitee.home}/security/truststore.jks
  #    password: secret
  
ldap:
  enabled: true
  context:
    # User to bind the LDAP
    user: svcGraviteeDev@medimpact.com
    # Password to bind the LDAP
    password: "shapooN0uf=eix&"
    # URL to LDAP
    url: ldap://ad.medimpact.com
    # Bind base to be used in authentication and lookup sections
    base: dc=medimpact,dc=com
  authentication:
    user:
      # Base to search users, must be relative to the context.base
      base: "ou=Users OU"
      # Use sAMAccountName if you are in AD
      # Use uid if you are in a native LDAP
      # The {0} will be replaced by user typed to authenticate
      filter: sAMAccountName={0}
      # If you have an attribute with the user photo, you can set it here
      # photo: "thumbnailPhoto"
    group:
      # Base to search groups, must be relative to the context.base
      # There an issue here, until fixed only oneleve search is supported
      base: ou=Secure Groups,ou=Groups OU
      # The {0} will be replaced by DN of the user
      filter: member={0}
      role:
        # The attribute that define your group names on your AD/LDAP
        # You can use sAMAccountName if you're in AD or cn if you're in native LDAP
        attribute: sAMAccountName
        consumer: "Gravitee Nonprod Consumer"
        publisher: "Gravitee Nonprod Publisher"
        admin: "Gravitee Nonprod Admin"
        monitor: "Gravitee Nonprod Monitor"
        user: "Gravitee Nonprod User"
  lookup:
    allowEmailInSearchResults: false
    # Note that personal information can be exposed without user consentment
    user:
      # Base to lookup user, must be relative to context.base
      base: "ou=Users OU"
      # The filter can be any type of complex LDAP query
      filter: (&(objectClass=person)(|(cn=*{0}*)(sAMAccountName={0})))
  
  
  
mongo:
  uri: mongodb://dv1medgravpoc1.medimpact.com:27017,dv1medgravpoc2.medimpact.com:27017,dv1medgravpoc3.medimpact.com:27017/gravitee?&connectTimeoutMS=30000&replicaSet=rs0&retryWrites=true&w=majority
mongodb-replicaset:
  enabled: false
portal:
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 4
  image:
    repository: docker-local.artifactory.medimpact.com/graviteeio/apim-portal-ui
    pullPolicy: IfNotPresent
    tag: 3.5.8
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - "gio-lab.medimpact.com"
    path: /
    tls:
      - hosts:
        - "gio-lab.medimpact.com"
  replicaCount: 3
  service:
    internalPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
smtp:
  enabled: true
  host: mx.medimpact.com
  from: gravitee-apim@medimpact.com
ui:
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 4
  companyName: "MedImpact"
  image:
    repository: docker-local.artifactory.medimpact.com/graviteeio/apim-management-ui
    pullPolicy: IfNotPresent
    tag: 3.5.8
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1$2
      # nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\n"
    hosts:
    - "gio-lab.medimpact.com"
    path: /console(/|$)(.*)
    tls:
      - hosts:
        - "gio-lab.medimpact.com"
  portal:
    apikeyHeader: "X-Api-Key"
    userCreation:
      enabled: true
    # support:
      # enabled: true
    rating:
      enabled: false
    analytics:
      enabled: false
      trackingId: ""
  replicaCount: 3
  service:
    internalPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi