---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azurechatgpt
  name: azurechatgpt
  # namespace: itsystems-dev
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: azurechatgpt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: azurechatgpt
    spec:
      containers:
      - name: azurechatgpt
        image: docker-local.artifactory.medimpact.com/com/medimpact/azurechatgpt-restricted:0.0.1
        imagePullPolicy: Always
        env:
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_API_INSTANCE_NAME
          value: "oai-gpt-dev-useast2-001"
        - name: AZURE_OPENAI_API_DEPLOYMENT_NAME
          value: "gpt-4-32k"
        - name: AZURE_OPENAI_API_VERSION
          value: "2023-03-15-preview"
        - name: AZURE_AD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: AZURE_AD_CLIENT_ID
        - name: AZURE_AD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: AZURE_AD_CLIENT_SECRET
        - name: AZURE_AD_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: AZURE_AD_TENANT_ID
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          value: "https://chatgpt-dev.medimpact.com"
        - name: AZURE_COSMOSDB_URI
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: AZURE_COSMOSDB_URI
        - name: AZURE_COSMOSDB_KEY
          valueFrom:
            secretKeyRef:
              name: azurechatgpt-secrets
              key: AZURE_COSMOSDB_KEY
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        # livenessProbe:
          # failureThreshold: 3
          # httpGet:
            # path: /healthz
            # port: 8080
            # scheme: HTTP
          # initialDelaySeconds: 30
          # periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        # readinessProbe:
          # failureThreshold: 3
          # httpGet:
            # path: /healthz
            # port: 8080
            # scheme: HTTP
          # initialDelaySeconds: 5
          # periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        resources:
          limits:
            cpu: "1000m"
            memory: "400Mi"
          requests:
            cpu: "0"
            memory: "300Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        # volumeMounts:
          # - name: models
            # mountPath: /llama.cpp/models
      securityContext:
        runAsUser: 10111
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      # volumes:
        # - name: models
          # persistentVolumeClaim:
            # claimName: modeltest-pvc