# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.devops-dev.bitbucket-dev
  # annotations:
    # volume.beta.kubernetes.io/mount-options: rsize=8192,wsize=8192,timeo=14,intr,vers=3
  labels: 
    volname: devops-dev.bitbucket-dev
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nfs
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_k8s_bitbucket_dev/k8s_bitbucket_dev"