# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itapps-confluence-dev
  namespace: itapps-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: nfs
  selector:
    matchLabels:
      volname: itapps-dev.itapps-confluence-dev
