# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-repo-dev
  namespace: sas-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: sas-dev.sas-repo-dev
