# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mms-qa-filedrop
  namespace: mms-qa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  selector:
    matchLabels:
      volname: mms-qa.mms-qa-filedrop
