# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdrp-appdata-qa-data-mdrp
  namespace: mfs-qa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mfs-qa.mdrp-appdata-qa-data-mdrp
