# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clmstore-dev
  namespace: clm-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 199Gi
  selector:
    matchLabels:
      volname: clm-dev.clmstore-dev
