# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mids-specialty
  namespace: mids-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mids-dev.mids-specialty
