# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata-dev-dev-data
  namespace: dmp-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: dmp-dev.appdata-dev-dev-data