# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defectdojo-dev
  namespace: defectdojo-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 160Gi
  #storageClassName: nfs
  selector:
    matchLabels:
      volname: defectdojo-dev.defectdojo-dev
