# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e1sonarqube-dev
  namespace: devops-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  #storageClassName: nfs
  selector:
    matchLabels:
      volname: devops-dev.e1sonarqube-dev