apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1medvfiler3-pafa-qa
  namespace: medresponse-qa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  selector:
    matchLabels:
      volname: medresponse-qa-pv1medvfiler3-pafa-qa