# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benefits-formulary-qa
  namespace: fmp-qa2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: fmp-qa2.benefits-formulary-qa