# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pylibs-nonprod
  namespace: ai-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: ai-dev.pylibs-nonprod