apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-basic-auth
  namespace: victoriametrics
type: Opaque
stringData:
  auth: consume:$apr1$B7Ak1icx$KhXLEBuOPoYkZT8t5cfJv0
  #IdNFZzvJn7M4VMW8DQzk