apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pbmpkafka-prod
  namespace: pbmp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  selector:
    matchLabels:
      volname: nfs-pbmp-pv1medvfiler4-pbmpkafka-caprod