apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-sentinel
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: config
        image: docker-local.artifactory.medimpact.com/dockerhub/redis:7.0.11-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_NAME
          value: redis
        - name: REDIS_PASSWORD
          value: "dok2maiNahX%"
        - name: SENTINEL_ID_0
          value: 1283b2a1777a57dcfb0edad810c7e8787ca57d98
        - name: SENTINEL_ID_1
          value: a85712599642686d845163893d81f1d1c649ca48
        - name: SENTINEL_ID_2
          value: 13884559b8c6d8c60d6bb4b27115c2dfbef5c59c
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: [ "sh", "-c" ]
        args:
          - |
            HOSTNAME="$(hostname)"
            SENTINEL_NAME="${HOSTNAME%-*}"
            INDEX="${HOSTNAME##*-}"
            eval MY_SENTINEL_ID="\${SENTINEL_ID_$INDEX}"
            MASTER_FQDN=${REDIS_NAME}-0.${REDIS_NAME}.${MY_NAMESPACE}.svc.cluster.local
            SLAVE_1_FQDN=${REDIS_NAME}-1.${REDIS_NAME}.${MY_NAMESPACE}.svc.cluster.local
            SLAVE_2_FQDN=${REDIS_NAME}-2.${REDIS_NAME}.${MY_NAMESPACE}.svc.cluster.local
            SENTINEL_0_FQDN=${SENTINEL_NAME}-0.${SENTINEL_NAME}.${MY_NAMESPACE}.svc.cluster.local
            SENTINEL_1_FQDN=${SENTINEL_NAME}-1.${SENTINEL_NAME}.${MY_NAMESPACE}.svc.cluster.local
            SENTINEL_2_FQDN=${SENTINEL_NAME}-2.${SENTINEL_NAME}.${MY_NAMESPACE}.svc.cluster.local
            POD_FQDN=$(hostname -f)
            echo "port 26379
            protected-mode no
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            sentinel announce-ip $POD_FQDN
            sentinel announce-port 26379
            sentinel monitor mymaster $MASTER_FQDN 6379 2
            sentinel down-after-milliseconds mymaster 3000
            sentinel failover-timeout mymaster 6000
            sentinel parallel-syncs mymaster 1
            sentinel auth-pass mymaster $REDIS_PASSWORD
            
            # Generated by CONFIG REWRITE
            user default on nopass ~* &* +@all
            dir "/data"
            sentinel myid $MY_SENTINEL_ID
            sentinel known-sentinel mymaster $SENTINEL_0_FQDN 26379 $SENTINEL_ID_0
            sentinel known-sentinel mymaster $SENTINEL_1_FQDN 26379 $SENTINEL_ID_1
            sentinel known-sentinel mymaster $SENTINEL_2_FQDN 26379 $SENTINEL_ID_2
            sentinel known-replica mymaster $SLAVE_1_FQDN 6379
            sentinel known-replica mymaster $SLAVE_2_FQDN 6379
            
            sentinel config-epoch mymaster 0
            sentinel leader-epoch mymaster 0
            sentinel current-epoch 0
            " > /etc/redis/sentinel.conf
            grep -v "sentinel known-sentinel mymaster $POD_FQDN" /etc/redis/sentinel.conf > /etc/redis/sentinel.tmp && mv /etc/redis/sentinel.tmp /etc/redis/sentinel.conf
            cat /etc/redis/sentinel.conf
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      containers:
      - name: sentinel
        image: docker-local.artifactory.medimpact.com/dockerhub/redis:7.0.11-alpine
        imagePullPolicy: IfNotPresent
        command: ["redis-sentinel"]
        args: ["/etc/redis/sentinel.conf"]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 26379 ping) == "PONG" ]; then exit 0;else exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(redis-cli -p 26379 ping) == "PONG" ]; then exit 0;else exit 1;fi
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 26379
          name: sentinel
        resources:
          limits:
            cpu: "1"
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: redis-config
        emptyDir: {}
  updateStrategy:
    type: RollingUpdate