---
apiVersion: v1
kind: Namespace
metadata:
  name: itsystems-lab
  labels:
    namespace: itsystems-lab
    istio-injection: disabled
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: itsystems-lab
spec:
  hard:
    limits.cpu: 20
    limits.memory: 9000M
    requests.cpu: 3000m
    requests.memory: 6000M
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: itsystems-lab
spec:
  limits:
  - default:
      cpu: 150m
      memory: 150Mi
    defaultRequest:
      cpu: 100m
      memory: 125Mi
    type: Container
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: itsystems-lab
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
# Allow istio prometheus to istio sidecars
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-istio-telemetry
  namespace: itsystems-lab
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: istio-system
        podSelector:
          matchLabels:
            app: prometheus
      ports:
      - port: 15090
        protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress