apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modeltest-pvc
  namespace: itsystems-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: itsystems-dev