---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-prometheus
  namespace: itsystems-lab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: minio-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio-prometheus
      name: minio-prometheus
    spec:
      containers:
      - image: docker-local.artifactory.medimpact.com/dockerhub/prom/prometheus:v2.36.0
        imagePullPolicy: IfNotPresent
        name: prometheus
        # command: ["/app/prometheus","--config.file","/app/config/prom.yaml","--web.listen-address",":9090","--storage.tsdb.path","/mnt/prom.data","--storage.tsdb.retention","3d"]
        args:
          - "--config.file=/app/config/prom.yaml"
          - "--web.listen-address=:9090"
          - "--storage.tsdb.path=/mnt/prom.data"
          - "--storage.tsdb.retention.time=10d"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "150m"
            memory: "256Mi"
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          # name must match the volume name below
          - name: prometheus-storage
            mountPath: "/mnt"
          - name: config
            mountPath: "/app/config"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1337
        fsGroup: 1337
      terminationGracePeriodSeconds: 30
      volumes:
      - name: prometheus-storage
        emptyDir: {}
      - configMap:
          defaultMode: 420
          items:
          - key: prom.yaml
            path: prom.yaml
          name: minio-prometheus
        name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-prometheus
  name: minio-prometheus
  namespace: itsystems-lab
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: minio-prometheus