apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db-dp1medex-scan
  namespace: pos-dev
spec:
  exportTo:
  - .
  hosts:
  - dp1medex-scan.medimpact.com
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 2025
    protocol: tcp
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dp1medexdb01-vip
  namespace: pos-dev
spec:
  exportTo:
  - .
  hosts:
  - dp1medexdb01-vip
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 2025
    protocol: tcp
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dp1medexdb02-vip
  namespace: pos-dev
spec:
  exportTo:
  - .
  hosts:
  - dp1medexdb02-vip
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 2025
    protocol: tcp
  resolution: NONE
