---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeltest
  name: modeltest
  namespace: itsystems-dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: modeltest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: modeltest
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while [ true ]; do sleep 10; done
        image: drydock.medimpact.com/itsystems/modeltest:v1
        imagePullPolicy: IfNotPresent
        name: modeltest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        # livenessProbe:
          # failureThreshold: 3
          # httpGet:
            # path: /healthz
            # port: 8080
            # scheme: HTTP
          # initialDelaySeconds: 30
          # periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        # readinessProbe:
          # failureThreshold: 3
          # httpGet:
            # path: /healthz
            # port: 8080
            # scheme: HTTP
          # initialDelaySeconds: 5
          # periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        resources:
          limits:
            cpu: "10000m"
            memory: "15Gi"
          requests:
            cpu: "2000m"
            memory: "12Gi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
          - name: models
            mountPath: /llama.cpp/models
      securityContext:
        runAsUser: 1337
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: modeltest-pvc