# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.corpcomm-prod.corp-sites-prod
  labels: 
    volname: corpcomm-prod.corp-sites-prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: nfs
  nfs:
    server: 10.15.130.120
    path: "/vol_pv2medvfiler4_corp_sites_prod/qtree_corp_sites_prod"
