# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.corpcomm-prod.manufdocs-prod-dest
  labels: 
    volname: corpcomm-prod.manufdocs-prod-dest
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.13.130.93
    path: "/vol_pv2medvfiler4_corpcomm_prod_manufdocs_prod_dest/qtree_manufdocs_prod"
