# Filename: pv-<storage type>-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs.corpcomm-uat.kyportal-uat
  labels: 
    volname: corpcomm-uat.kyportal-uat
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_corpcomm_kyportal_uat/qtree_kyportal_uat"