# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: formulary-extract-e2e74
  namespace: fxa-e2e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      volname: fxa-e2e.formulary-extract-e2e74
