# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngpa-prod-mirror
  namespace: pas-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volname: pas-prod.ngpa-prod-mirror
