# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfs-e2e-mdrp
  namespace: mfs-e2e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mfs-e2e.mfs-e2e-mdrp
