# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e1sonarqube-prod
  namespace: devops-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      volname: devops-prod.e1sonarqube-prod