# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mids-specialty
  namespace: mids-uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mids-uat.mids-specialty
