# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corp-sites-prod
  namespace: corpcomm-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: corpcomm-prod.corp-sites-prod
