# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rad-e2e
  namespace: medadjust-e2e
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6.5Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: medadjust-e2e.rad-e2e
