apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencve-crazy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencve-crazy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opencve-crazy
    spec:
      containers:
      - name: webserver
        image: docker-local.artifactory.medimpact.com/com.medimpact/itsec/opencve:1.4.1
        imagePullPolicy: Always
        args: ["webserver", "-b", "0.0.0.0:8000"]
        envFrom:
        - configMapRef:
            name: opencve-env
        livenessProbe:
          httpGet:
            path: /static/img/favicon.ico
            port: 8000
            httpHeaders:
            - name: Host
              value: opencve-dev.medimpact.com
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /static/img/favicon.ico
            port: 8000
            httpHeaders:
            - name: Host
              value: opencve-dev.medimpact.com
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1000m"
            memory: "300Mi"
          requests:
            cpu: "0"
            memory: "200Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: config
          mountPath: /app/config
      - name: celery-worker
        image: docker-local.artifactory.medimpact.com/com.medimpact/itsec/opencve:1.4.1
        imagePullPolicy: Always
        args: ["celery-worker"]
        envFrom:
        - configMapRef:
            name: opencve-env
        resources:
          limits:
            cpu: "1000m"
            memory: "800Mi"
          requests:
            cpu: "0"
            memory: "500Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: config
          mountPath: /app/config
      - name: celery-beat
        image: docker-local.artifactory.medimpact.com/com.medimpact/itsec/opencve:1.4.1
        imagePullPolicy: Always
        args: ["celery-beat"]
        envFrom:
        - configMapRef:
            name: opencve-env
        resources:
          limits:
            cpu: "1000m"
            memory: "400Mi"
          requests:
            cpu: "0"
            memory: "300Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: config
          mountPath: /app/config
      - name: postgres
        image: docker-local.artifactory.medimpact.com/dockerhub/postgres:15.1
        # image: docker-local.artifactory.medimpact.com/dockerhub/postgres:15.4
        # image: docker-local.artifactory.medimpact.com/dockerhub/postgres:11.21-bullseye
        imagePullPolicy: IfNotPresent
        # lifecycle:
          # preStop:
            # exec:
              # command:
                # - /bin/sh
                # - -c
                # - sleep 10
        args:
        - -c
        - max_connections=500
        - -c
        - shared_buffers=140MB
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/db-data
        - name: POSTGRES_DB
          value: opencve
        - name:  POSTGRES_PASSWORD
          value: goodpassword
        - name:  POSTGRES_USER
          value: opencve
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "1000m"
            memory: "800Mi"
          requests:
            cpu: "0"
            memory: "400Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: opencve-postgres-data
      - name: config
        configMap:
          name: opencve-crazy-config
      securityContext:
        runAsUser: 10222
        runAsGroup: 10222
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
kind: Service
apiVersion: v1
metadata:
  name: opencve-crazy
spec:
  selector:
    app: opencve-crazy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000