---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-lab
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: jenkins-lab
spec:
  hard:
    limits.cpu: 18000m
    limits.memory: 4G
    requests.cpu: 2000m
    requests.memory: 4G
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: jenkins-lab
spec:
  limits:
  - default:
      cpu: 150m
      memory: 125M
    defaultRequest:
      cpu: 50m
      memory: 100M
    type: Container
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: jenkins-lab
spec:
  podSelector: {}
---
# Allow istio prometheus to istio sidecars
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-istio-telemetry
  namespace: jenkins-lab
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: istio-system
        podSelector:
          matchLabels:
            app: prometheus
      ports:
      - port: 15090
        protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
---
#bind AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_aws_jenkins-lab
  namespace: jenkins-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kube_aws_jenkins-lab