apiVersion: v1
metadata:
  name: prometheus
  namespace: vault-dev
kind: ConfigMap
data:
  vault.yaml: |
    global:
      scrape_interval: 20s
    scrape_configs:
      - job_name: 'vault'
        metrics_path: "/v1/sys/metrics"
        # vault_route_(method)_(engine)_
        # vault_route_(method)_(engine)__count
        # vault_route_(method)_(engine)__sum
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: '(vault_route)_([[:alnum:]]+)_(.*[[:alnum:]]+)_(.*)'
          replacement: '${2}'
          target_label: method
        - source_labels: [__name__]
          regex: '(vault_route)_([[:alnum:]]+)_(.*[[:alnum:]]+)_(.*)'
          replacement: '${3}'
          target_label: engine
        - source_labels: [__name__]
          regex: '(vault_route)_([[:alnum:]]+)_(.*[[:alnum:]]+)_(.*)'
          replacement: '${1}_method_${4}'
          target_label: __name__
        params:
          format: ['prometheus']
        scheme: https
        tls_config:
          # ca_file: your_ca_here.pem
          insecure_skip_verify: true
        bearer_token: "your_vault_token_here"
        static_configs:
        - targets: ['vault-az.medimpact.com:8200','vault-ca.medimpact.com:8200','vault-dev.medimpact.com:8200']