kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opencve-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: itsec-dev