# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benefits-formulary-prod
  namespace: dmp-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: dmp-prod.benefits-formulary-prod