# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfs-demo-mdrp
  namespace: mfs-uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mfs-uat.mfs-demo-mdrp
