# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mms-prod-filedrop-mirror
  namespace: mms-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: mms-prod.mms-prod-filedrop-mirror
