---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:pmm-service-account
  labels:
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:pmm-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:pmm-service-account
subjects:
- kind: ServiceAccount
  name: pmm-service-account
  namespace: itsystems-lab