---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gio-apim3-gateway
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: api-lab.medimpact.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gio-apim3-gateway
                port:
                  number: 82
    - host: api-strict-lab.medimpact.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gio-apim3-gateway
                port:
                  number: 82
    - host: api-intra-lab.medimpact.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gio-apim3-gateway
                port:
                  number: 82
    - host: api-dev.medimpact.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gio-apim3-gateway
                port:
                  number: 82
    - host: api-qa.medimpact.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gio-apim3-gateway
                port:
                  number: 82
  tls:
    - hosts:
      - api-lab.medimpact.com
      - api-strict-lab.medimpact.com
      - api-intra-lab.medimpact.com
      - api-dev.medimpact.com
      - api-qa.medimpact.com