apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencve-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencve-celery-worker
  template:
    metadata:
      labels:
        app: opencve-celery-worker
    spec:
      containers:
      - name: celery-worker
        # image: docker-local.artifactory.medimpact.com/com.medimpact/itsec/opencve:1.4.1-mi0.0.1
        image: docker-local.artifactory.medimpact.com/com.medimpact/itsec/opencve:1.4.1
        imagePullPolicy: Always
        args: ["celery-worker"]
        envFrom:
        - configMapRef:
            name: opencve-env
        resources:
          limits:
            cpu: "1000m"
            memory: "800Mi"
          requests:
            cpu: "0"
            memory: "500Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: config
          mountPath: /app/config
      securityContext:
        runAsUser: 10222
        runAsGroup: 10222
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        # sysctls:
        # - name: "net.ipv4.tcp_keepalive_time"
          # value: "600"
      volumes:
      - name: config
        configMap:
          name: opencve-config
# ---
# kind: Service
# apiVersion: v1
# metadata:
  # name: celery-worker
# spec:
  # selector:
    # app: celery-worker
  # ports:
    # - protocol: TCP
      # port: 80
      # targetPort: 80