---
apiVersion: v1
kind: Secret
metadata:
  name: vmwareq
  namespace: itsystems-prod
stringData:
  vcenters.yaml: |
    VCenters:
      - Name: SRO1
        Host: pv2medvcenter1.medimpact.com
        Username: svcVMQueryApp@medimpact.com
        Password: M,ymu-Pfa}=w?4~
      - Name: WTD1
        Host: pv1medvcenter1.medimpact.com
        Username: svcVMQueryApp@medimpact.com
        Password: M,ymu-Pfa}=w?4~