apiVersion: v1
metadata:
  name: vmwareq
  namespace: itsystems-prod
kind: ConfigMap
data:
  config.yaml: |
    Port: "8080"
    SSLPort: "8443"
    UseSSL: false
    SSLPublicKey: ./certs/terra-cert.pem
    SSLPrivateKey: ./certs/terra-key.pem
    ClientID: 2d610b54-fc37-4fd2-b38b-cb344301b98a
    ClientSecret: Rl7w4wGmFJQnewkZc-YSLAHii5-A8DeuE4Y-i-9-
    RedirectURI: https://vmwareq.medimpact.com/callback
    IssuerURL: https://sts.medimpact.com/adfs
    UseRedisSessions: true
    RedisHost: vmwareq-redis
    RedisPort: 6379
    SessionLength: 28800 #12 hours (ideally should not be longer than ADFS token expiration: 8hrs)
    ADGroup: Domain Users