apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1medvfiler3-pafa-dev
  namespace: medresponse-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  selector:
    matchLabels:
      volname: medresponse-dev-pv1medvfiler3-pafa-dev