# Filename pvc-<namespace>-<volume name>.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-logs-dev
  namespace: bia-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volname: bia-dev.superset-logs-dev
