apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ppdl-dev
  namespace: dmp-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName: nfs
  selector:
    matchLabels:
      volname: dmp-dev.ppdl-dev