apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.42.0
  name: k8s
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: additional-scrape-configs.yaml
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  enableFeatures: []
  externalUrl: /prometheus/
  externalLabels:
    region: ca
    cluster: calab
  image: quay.io/prometheus/prometheus:v2.42.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.42.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 1500Mi
  retention: 12h
  ruleNamespaceSelector: {}
  ruleSelector: {}
  secrets:
    - etcd-certs
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.42.0
  remoteWrite:
  - url: "https://k8cadev.medimpact.com/vminsert/insert/0/prometheus"
    basicAuth:
      username:
        name: prometheus-remotewrite-victoriametrics
        key: username
      password:
        name: prometheus-remotewrite-victoriametrics
        key: password
    writeRelabelConfigs:
      - action: labeldrop
        regex: prometheus_replica
    queueConfig:
      batchSendDeadline: 5s
      capacity: 20000 #default = 2500 Should be about 3x maxSamplesPerSend
      maxSamplesPerSend: 10000 #default = 100
      minBackoff: 30ms
      maxBackoff: 30s
      minShards: 1
      maxShards: 50 #default 200
      # retry_on_http_429: true # expiremental and not supported yet