---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: linkerd-control-plane-internal
  namespace: pos
spec:
  podSelector:
    matchLabels:
      linkerd.io/control-plane-ns: pos
  ingress:
    - from:
      - podSelector:
          matchLabels:
            linkerd.io/control-plane-component: ca
      - podSelector:
          matchLabels:
            linkerd.io/control-plane-component: controller
      - podSelector:
          matchLabels:
            linkerd.io/control-plane-component: grafana
      - podSelector:
          matchLabels:
            linkerd.io/control-plane-component: prometheus
      - podSelector:
          matchLabels:
            linkerd.io/control-plane-component: web
      # ports:
      # - port: 4143
        # protocol: TCP
