apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-all-configs
  namespace: pos
data:
  DrugPricer.cfg: |-
    ;use semi-colon for comments
    [DRUGPRICER]
    ;ROUTER_HOST is the hostname where service router is running.
    ROUTER_HOST=pos-service-router
    ;ROUTER_PORT is the port on which service router is running.
    ROUTER_PORT=49500
    ;SERVICE is the name of the service which will be registered with the router.
    SERVICE=DRUG_PRICER
    ;DATABASE to which Worker will be connected to for processing.
    DATABASE=devh01
    ;USERNAME is the database user name.
    USERNAME=posgroup
    ;PASSWORD is the database password.
    PASSWORD=co0rdin8
    ;LOGFORMAT is the LOG4CPLUS format for logging.
    LOGFORMAT=%D{%m%d%y|%H:%M:%S.%q}|%x|%-8p|%i|%m%n
    ;LOGLEVEL is the LOG4CPLUS level. When set to ALL detailed logging will be done.Production should be set to INFO.
    LOGLEVEL=INFO
    ;POS_TRACE when set to 1 will log the pos trace in the log file.
    POS_TRACE=0
    ;POS_OVR is the override name setup in the database.
    POS_OVR=DRUGPRCR
    ; List of error codes we will return price along with
    ERROR_CODES=75,60,9G,76,608
    ;Number of times we should try to reconnect to the service router
    ROUTER_RECONNECT=5
    ;Number of beats we should wait before sending hearbeat message
    HEARTBEAT_LIVENESS=10
    ;Interval between beats
    HEARTBEAT_INTERVAL=6000
  drug_pricer_soap.cfg: |-
    # The port this service will listen on
    LISTEN_PORT=49202

    # The directory where the WSDL (and any xsd includes) resides
    WSDL_LOCATION=/opt/pos/doc/WSDL

    # The WSDL file
    WSDL=DrugPrice-v1_0.wsdl

    # The route for the service (the URL path)
    SERVICE_ROUTE=/drug_price_interactive/DrugPrice-v1_0

    # The name of the service you're requesting
    SERVICE_NAME=DRUG_PRICER

    # The host the where the medcom broker is located
    SERVICE_ROUTER_HOST=pos-service-router

    # The port at which the medcom broker is listening
    SERVICE_ROUTER_PORT=49500

    # The time limit to wait for a response, in milliseconds
    RESPONSE_TIMEOUT=25000

    # The level of logging to emit
    # Choices: INFO or TRACE
    LOG_LEVEL=INFO
  pos_service_messages.cfg: |-
    E001=Member Not found
    E002=Carrier HQ Not Found
    E000=Internal Server Error
    E003=Service Unavailable
    E004=One of the required element not provided in the request
    E005=Input Format Error
    E006=Benefit Not Found
    E007=Group Company Not Found
    E008=Carrier Not Found
  service_router.cfg: |-
    # PORT tells the router which port to listen on for client connections.
    # Can be numeric or a service name listed in /etc/services.

    PORT=49500

    # MONITOR_PORT tells the router which port to listen on for runtime
    # monitoring connections. This port outputs runtime stats for users
    # who want to see what's going on internally.
    # Can be numeric or a service name listed in /etc/services.

    MONITOR_PORT=49501

    # HEARTBEAT_LIVENESS is the number of times to check for a HEARTBEAT
    # message from any service worker before assuming the worker is no
    # longer alive. 3 - 5 is reasonable. If you have to set this to more than
    # that, then your service is probably too slow and unresponsive.
    # Default is 5.

    HEARTBEAT_LIVENESS=10

    # HEARTBEAT_INTERVAL is the time interval, in milliseconds, to wait between
    # checking for heartbeats.
    # Default is 2500 milliseconds.

    HEARTBEAT_INTERVAL=6000

    # LOG_LEVEL tells us how much info to display as it runs.
    # The following levels are supported:
    #
    # OFF: Log nothing.
    # ALL: Display  as much as possible.
    # INFO: Only display exceptions and a small amount of data usefull
    # for troubleshooting production.
    # Default is INFO.

    LOG_LEVEL=INFO


    # LOG_FORMAT controls the format of the log entries written.
    # See log4cplus documentation for help on format specifiers.
    # Default is: %x|%D{%d%m%y|%H:%M:%S%q}|%-8p|%i|%m%n

    LOG_FORMAT=%x|%D{%d%m%y|%H:%M:%S%q}|%-8p|%i|%m%n
  tnsnames.ora: |-
    devh01 =
      (DESCRIPTION =
        (ADDRESS =
          (PROTOCOL = TCP)
          (Host = dp1medex-scan)
          (Port = 2025)
        )
        (CONNECT_DATA = (SERVICE_NAME = D1POSTC)
          (SERVER = DEDICATED)
        )
      )