---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-vault-auth
  namespace: vault-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: external-vault-auth-token
  namespace: vault-dev
  annotations:
    kubernetes.io/service-account.name: external-vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: vault-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: external-vault-auth
    namespace: vault-dev