---
apiVersion: v1
kind: Namespace
metadata:
  name: pas-dev
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "kubernetes.azure.com/scalesetpriority", "Operator": "Equal", "Value": "spot", "Effect": "NoSchedule"}]'
  labels:
    pod-security.kubernetes.io/enforce: restricted
    namespace: pas-dev
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: pas-dev
spec:
  hard:
    limits.cpu: 80000m
    limits.memory: 50G
    requests.cpu: 9000m
    requests.memory: 24G
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: pas-dev
spec:
  limits:
  - default:
      cpu: 150m
      memory: 125M
      ephemeral-storage: 5Gi
    defaultRequest:
      cpu: 10m
      memory: 100M
      ephemeral-storage: 100Mi
    max:
      ephemeral-storage: 10Gi
    type: Container
---
# Allow istio prometheus to istio sidecars
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-istio-telemetry
  namespace: pas-dev
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: istio-system
        podSelector:
          matchLabels:
            app: prometheus
      ports:
      - port: 15090
        protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: pas-dev
spec:
  podSelector: {}
---
#bind AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_prod_pas-dev
  namespace: pas-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  namespace: pas-dev
  name: 6b396617-d21f-472b-afbc-5e153aed1a6d
---
#bind power-users AD group to the management role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc:kube_cluster-power-users
  namespace: pas-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: medimpact:namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  namespace: pas-dev
  name: 5becc647-277b-422b-b385-8b9ba00d9b5e