apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pas-dev-pas-rules-pub-ws
spec:
  destination:
    name: aks-dev-westus2-001
    namespace: pas-dev
  revisionHistoryLimit: 10
  project: pas-nonprod
  source:
    path: kubernetes/aks-dev
    repoURL: https://bitbucket.medimpact.com/scm/pas/pas-rules-pub-ws.git
    targetRevision: development
  syncPolicy:
    syncOptions:
      - CreateNamespace=false