apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pbmp-qa-pv1medvfiler4-pbmpkafka-nonprod
  # annotations:
    # volume.beta.kubernetes.io/mount-options: rsize=8192,wsize=8192,timeo=14,intr,vers=3
  labels: 
    volname: nfs-pbmp-qa-pv1medvfiler4-pbmpkafka-nonprod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.13.130.93
    path: "/vol_pv1medvfiler4_pbmpkafka_nonprod/qtree_pbmpkafka_nonprod"