apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-repo-creds
  namespace: argocd-dev
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  username: svcArgoCDDev
  password: fuG3dae7Quu&
  url: https://bitbucket.medimpact.com/scm