apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: bitbucket.medimpact.com-scm-pas-pas-process-ws.git
stringData:
  type: git
  # username: svcArgoCDDev
  # password: fuG3dae7Quu&
  url: https://bitbucket.medimpact.com/scm/pas/pas-process-ws.git