{
 "title": "Etcd",
 "description": "etcd sample Grafana dashboard with Prometheus",
 "tags": [ "etcd" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",cluster=~\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",cluster=~\"$cluster\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",cluster=~\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",cluster=~\"$cluster\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration (99 percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{cluster=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{cluster=~\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster=~\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Headless alerts - local cluster only",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Leader Elections Per Day",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
       "legendFormat": "{{instance}} Total Leader Elections Per Day"
      }
     ]
    }
   ]
  }
 ]
}