---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: argocd
# ---
# apiVersion: v1
# kind: Secret
# metadata:
  # name: argocd-token
  # namespace: argocd
  # annotations:
    # kubernetes.io/service-account.name: argocd
# type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd
subjects:
- kind: ServiceAccount
  name: argocd # Name is case sensitive
  namespace: argocd
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: argocd-application-controller # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
