apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-repo-creds
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  # username: svcArgoCDDev
  # password: fuG3dae7Quu&
  # url: https://bitbucket.medimpact.com/scm
  url: ssh://git@bitbucket.medimpact.com
  sshPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAyihFXUuwoAyyfmRRVtDtj63+ztJ68cRm+oHuIamx/8VXkOwI
    W4xOSuSz5dCzKXi6aWBiY4SiTUszsSmVRr3xNkpmzmtrE5s3VlmOdKV1AttklHJb
    FgVlCXpZyqq3N4iWp0lXmvPBMaZTJlTa6YlMAUwrnJbYiKQvqOskrHohzv9GhCl3
    MM9ScsGuUKbz571GFB5K6kvIWEtpfwBVsOMR9SQZk0BDKFWRzHCH8pquyIP+TZjd
    DF39gMOm2uESwgl2LBc8Im4Lg5U7Is9O0IRySzQlnuUXKvejhWr0D8iSX31/cEAd
    QUX8pvaqQNPUz0YJARKuoZ4b6GOCkeExB9d1AwIBIwKCAQBFT6LA5sA238grVZg7
    Bc3K3JHggq3PPAYMvtVNXsCvdtwxsALdjzDJOHgxiWH/lxtXVD79jI9q9TZLXrbW
    bQI+f+i7zQ7E5MKEAXKrpnFCzuCn7LGD5Jeremfttt+7RMXwNmctz+p3bDnD/9YG
    7T6hW/GyB9U2KanwxaYsgaUxBnSJeV68cqHc0lkADfSPaI8mBmIUUHbXB0gxj/l1
    Zazp78kSbn7zkjPHKRFj6oUyR/6D2u47V9hCBCpGVYAM2X3TB6lnzsjQGHAZdsmr
    L0czDhJ6Y/tgcmsd3fztM7uZ/Imp4TEL3Kp9dv9g1ftLwFObAR31BZIXgp/BTMh9
    tKJLAoGBAPLRgOht+DHJjj4c1nJWBPfEvLe4ZFNzA9gobePrcdQLRXqt8HlNGr8Y
    VOEF+leFjhFLExuY2udQDTBwo38L47RjZn7HT/f9w6v61EWum1sPLQowYxv9xsSI
    XRoQ2MHufCnS3gMGgzK1XcrJKCHJvWSzrNvBaAIjvQEtbVEF0vGbAoGBANUhsTpy
    iMiPzeyeUnhEx1d1zvUhUhpHclQbWS+EXgWU4z8aOCzqJbuvOTQz3v1wTpwB8d/x
    GDTFf6XHxDOQq2ghL7nsWEnRikgzCzzunzI8c2WJiQipOHvl8Q2gbkKai27DO/XY
    KdiuUyFH5kC97QXJTTuAOy+qvtobU+yTYFS5AoGBAIPQ0PM0Yimn7iG34iDPnEv9
    Ff1VeEqO5NRtt/9ijj/o3JMN95JObZrv85AZMCDiGewhcMXWorgVg4CyLN6RbPuG
    atcbvbKCcYk/BYTpwgzcWkdcGIuJw6yEik/6hEwFHtTgL2C6ZHqc+GbE+Ide4ygJ
    xDzIE+Png9wRWJmytFdFAoGBAKRqcsawIGA0a6fn2Tg1Ds5w0tpbiHqsJP8NyHUc
    +BLvMvYqK1XZMw0gxbqOajE5YTaFKE2rW9DwIKR1iLoQhDpivmra5QW+5wR/Je0t
    G7kKD+CdTHRlSNSbcM//awAuE8p5WiQNJ5iGeqSlLfdt8Vw8NEPX8yTFi+oVFNsS
    msUDAoGBAJWs9JRRNXagJ3+GQnOq1SqWXKy6jEGQLbKAQossV6pHbuIThbxnXMqO
    Mh79iU6XqV6XYY2qN382cj+FzubKxDVxK9fQZvCqLSQlnfFnaqu/3nE1vfHrTHhH
    KuaEnED+234NcE4GOwBwv/GQabAcu9uvYt2Mh9OMFe8sjSDn8Srq
    -----END RSA PRIVATE KEY-----