apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-itsys-001
  namespace: itsystems-lab
data:
  enabled_plugins: |
    [rabbitmq_management].
      
  rabbitmq.conf: |
    ## Cluster formation. See https://www.rabbitmq.com/cluster-formation.html to learn more.
    #cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    
    # DNS method uses A record query on k8s svc
    cluster_formation.peer_discovery_backend = dns
    cluster_formation.dns.hostname = $(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
    
    # Tried and true option:
    # cluster_formation.peer_discovery_backend = classic_config
    # cluster_formation.classic_config.nodes.1 = rabbit@$(MY_STS_NAME)-0.$(K8S_SERVICE_NAME).itsystems-lab.svc.cluster.local
    # cluster_formation.classic_config.nodes.2 = rabbit@$(MY_STS_NAME)-1.$(K8S_SERVICE_NAME).itsystems-lab.svc.cluster.local
    # cluster_formation.classic_config.nodes.3 = rabbit@$(MY_STS_NAME)-2.$(K8S_SERVICE_NAME).itsystems-lab.svc.cluster.local
    
    # Retry peer discovery operations up to this many times
    cluster_formation.discovery_retry_limit = 300
    # # 1000 milliseconds
    cluster_formation.discovery_retry_interval = 1000
    
    #cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    ## Should RabbitMQ node name be computed from the pod's hostname or IP address?
    ## IP addresses are not stable, so using [stable] hostnames is recommended when possible.
    ## Set to "hostname" to use pod hostnames.
    ## When this value is changed, so should the variable used to set the RABBITMQ_NODENAME
    ## environment variable.
    log.file = false
    log.console = true
    log.console.level = info
    #cluster_formation.k8s.address_type = hostname
    
    ## How often should node cleanup checks run?
    cluster_formation.node_cleanup.interval = 30
    
    ## Set to false if automatic removal of unknown/absent nodes
    ## is desired. This can be dangerous, see
    ##  * https://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup
    ##  * https://groups.google.com/forum/#!msg/rabbitmq-users/wuOfzEywHXo/k8z_HWIkBgAJ
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    
    ## See https://www.rabbitmq.com/ha.html#master-migration-data-locality
    queue_master_locator=min-masters
    
    ## This is just an example.
    ## This enables remote access for the default user with well known credentials.
    ## Consider deleting the default user and creating a separate user with a set of generated
    ## credentials instead.
    ## Learn more at https://www.rabbitmq.com/access-control.html#loopback-users
    # loopback_users.guest = false
    
    vm_memory_high_watermark.absolute = $(RABBITMQ_MAX_MEM)
    
    cluster_name = $(RABBITMQ_CLUSTER_NAME)
    
    default_user = $(RABBITMQ_USERNAME)
    default_pass = $(RABBITMQ_PASSWORD)