apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pbmp-pv2medvfiler4-pbmpkafka-azprod
  # annotations:
    # volume.beta.kubernetes.io/mount-options: rsize=8192,wsize=8192,timeo=14,intr,vers=3
  labels: 
    volname: nfs-pbmp-pv2medvfiler4-pbmpkafka-azprod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rsize=8192
    - wsize=8192
    - timeo=14
    - intr
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.15.130.119
    path: "/vol_pv2medvfiler4_pbmpkafka_azprod/qtree_pbmpkafka_azprod"