---
apiVersion: v1
kind: Namespace
metadata:
  name: itsystems-prod
  # annotations:
    # scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "kubernetes.azure.com/scalesetpriority", "Operator": "Equal", "Value": "spot", "Effect": "NoSchedule"}]'
  labels:
    pod-security.kubernetes.io/enforce: restricted
    namespace: itsystems-prod
---
#total namespace quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-limit
  namespace: itsystems-prod
spec:
  hard:
    limits.cpu: 60000m
    limits.memory: 76G
    requests.cpu: 12000m
    requests.memory: 60G
---
#individual container defaults
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: itsystems-prod
spec:
  limits:
  - default:
      cpu: 150m
      memory: 125M
      ephemeral-storage: 5Gi
    defaultRequest:
      cpu: 50m
      memory: 100M
      ephemeral-storage: 100Mi
    max:
      ephemeral-storage: 20Gi
    type: Container
---
#default deny network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: itsystems-prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress